### ISSUE TITLE
Produce guidance on data modeling

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#101]
Because of the feedback in #77, we have identified the need to produce guidance on data modeling that accommodates GeoPackage's one-geometry-column restriction. This guidance will be published on geopackage.org.

**Comment by jyutzler** [comment]
@trgn We agreed for you to take a shot at the following three cases:
   1. secondary tables for multi-scale representations
   1. grouping features for aggregations
   1. historical versions of the same feature

I don't think I can formally assign this to you in GitHub until you become a member of the OGC GitHub organization. Talk to @gbuehler about that.

**Comment by trgn** [comment]
Is an early/mid august 2015 delivery date for this acceptable? thx

**Comment by jyutzler** [comment]
@trgn We're all volunteers here. The sooner the better but no one is forcing anyone to do anything. That said, if anyone else wants to take a shot at this that would be fine too.

**Comment by trgn** [comment]
I posted an initial draft here:
https://www.dropbox.com/s/v5myukrsxt561z9/GeopackageDataModelingGuidelines.docx?dl=0

It still requires:
- show example of gpkg_* contents for each use case
- show example of how views can make the geopackage more user-friendly

I'll add this in the coming days.

**Comment by trgn** [comment]
updated the draft.

@jyutzler  you'd asked me earlier to upload this to a OGC site. Is this the https://portal.opengeospatial.org/?m=files? site?

Also, is there any official OGC templating that needs to applied to the document?

**Comment by jyutzler** [comment]
The thing to do here is to add it to geopackage.org under a subpage. With it on GitHub, it is available to the public and we can maintain it as necessary. I asked the OGC back end guys what the best way is to go from your word document to the stylesheet used in gh-pages/index.html.

**Comment by jyutzler** [comment]
See http://www.geopackage.org/modeling_guidelines.html
