### ISSUE TITLE
table_name is an FK

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#111]
From Michael Gerlek http://www.slideshare.net/mpgx/geo-package-pointclouds slide 15

> Table 17
> Addition: table_name is an FK

I'm not sure if we want to change this one.

**Comment by pepijnve** [comment]
Making table_name a foreign key (to gpkg_contents I assume) might be a bit too restrictive. It implies that you can only apply extensions to user data tables.

**Comment by jyutzler** [comment]
At today's SWG we were unable to identify any benefit to making this an FK and determined that it would potentially break some existing GeoPackages. Therefore, we agreed not to pursue this change.
