### ISSUE TITLE
Consider PNG as a format for integer data

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#113]
Some research from the Army Globe Engine folks suggests that PNG may be a superior data format than LZW-compressed TIFF files.
[More details here.](https://portal.opengeospatial.org/files/?artifact_id=64147)

**Comment by pepijnve** [comment]
16-bit grayscale PNGs is what we were using at Luciad as well in our pre-geopackage format. Works great, but is limited to 16-bit. When you need higher precision or floating point TIFF is needed.

**Comment by pepijnve** [comment]
@jyutzler do you happen to know if the TIFF compressor was using the horizontal differencing predictor? That should improve compression a bit. Not as good as PNG probably though.

**Comment by jyutzler** [comment]
At today's SWG we agreed to have separate approaches for TIFF and PNG. PNG would be used for integer/16-bit data and TIFF would be used for floating point data. I have some documenting to do.
