### ISSUE TITLE
Populate Extensions table for elevation extension

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#119]
The specification currently lacks information regarding what belongs in the gpkg_extensions table.

* For the general extension, I think a single row with no table/column is sufficient because the extension doesn't change the behavior of any table (particularly if #120 is adopted)
* For the TIFF extension, the `tile_data` column of each tile pyramid user data table.

**Comment by jyutzler** [comment]
See reversal branch https://github.com/opengeospatial/geopackage-elevation/tree/reversal/spec

**Comment by jyutzler** [comment]
I received this over email. I'm neutral. What do you think?

---------------------
It might make more sense to fill out the gpkg_extensions table as follows:

table_name|column_name|extension_name|definition|scope
----------------|-------------------|----------------------|------------|---------------
gpkg_2D_gridded_coverage_ancillary|null|gpkg_elevation_tiles|TBD [7]|read-write
gpkg_2D_gridded_tile_ancillary|null|gpkg_elevation_tiles|TBD [7]|read-write

From "2.5.2.1.1. Table Definition"  

table_name

TEXT

Name of the table that requires the extension. When NULL, the extension is required for the entire GeoPackage. SHALL NOT be NULL when the column_name is not NULL.


Since the extension is only needed to read those 2 tables and not required for the "entire GeoPackage". (This is a little fuzzy because we set the value of gpkg_contents.data_type  to 2D-gridded-coverage and "reuse" the base spec tables)

**Comment by pepijnve** [comment]
IMO you would want to 'apply' the extension to the tiles user data table containing elevation data. The table is different from standard ones in the sense that it does not represent RGB data.

If you do not flag the elevation table as non-standard then it's perfectly valid for a reader to read/write the elevation data as RGB. If that's intentional then there's no issue. If you want to avoid this, then the extension needs to be applied to the user data table. That's the whole purpose of the extensions table.

**Comment by jyutzler** [comment]
In today's SWG, we agreed that ancillary tables should be referenced in the extensions table, not the data tables. Note that since the elevation data has a different `data_type` in `gpkg_contents`, the data won't be found by clients that do not conform to this extension.

Either way, I don't think this is a huge deal. The important fact is that leaving the `table_name` blank implies that you need the extension to read anything in the database. We all agree that is wrong.

[master fa4de8e] changing extensions table entries #119

**Comment by bradh** [comment]
Note that the assumptions that underpin this decision are invalid on at least the current implementation of GDAL. If the table is not listed in gpkg_extensions, then GDAL assumes it can open that table without extension support.

**Comment by pepijnve** [comment]
@bradh elevation data is marked as `2D-gridded-coverage` in `gpkg_contents`. Are you sure GDAL tries to open that? I would expect it to only pick up `features` and `tiles`.

**Comment by bradh** [comment]
@pepijnve Indeed. My bad - an error in the way I encoded the file (well, forgot to remove the test hack).
