### ISSUE TITLE
remove lowercase from sentence in 2.1.6.1.2

### ISSUE THREAD

**Issue by KRyden** [opengeospatial/geopackage#144]
Section 2.1.6.1.2. Table Data Values reads as follows:

A feature geometry is stored in a geometry column specified by the lowercase geometry_column value for the feature table in thegpkg_geometry_columns table defined in clause Geometry Columns above.

In this statement, the geometry_column is called out as lowercase.  The OGC Geopackage specification states that Geopackage spec tables and columns are to be lowercase, but does not have the same restriction on user created tables/columns.  Our read is that the lowercase term in the sentence above should be removed – it’s a user defined geometry_column/feature_table.  

The sentence should read:

A feature geometry is stored in a geometry column specified by the geometry_column value for the feature table in thegpkg_geometry_columns table defined in clause Geometry Columns above.

**Comment by jyutzler** [comment]
Today the SWG agreed to this.
