### ISSUE TITLE
Missing close-parens in Annex M (geometry type trigger extension) 

### ISSUE THREAD

**Issue by TheDorkKnight** [opengeospatial/geopackage#152]
See [pull request 151](https://github.com/opengeospatial/geopackage/pull/151) for my proposed fix.

The template SQL for creating geometry type triggers is missing a closing parenthesis for both the INSERT and the UPDATE trigger definitions.

Implementers of Annex M have noticed this and have added the missing parentheses. See [libspatialite](https://www.gaia-gis.it/fossil/libspatialite/index) (as of version 4.3.0a) for an example. They have implemented Annex M in src/geopackage/gpkg_add_geometry_triggers.c

**Comment by jyutzler** [comment]
fixed via #151
