### ISSUE TITLE
Define "glob"

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#156]
In the [schema section](http://www.geopackage.org/spec/#_schema) we use the term "glob" but it is never defined. Defining this term would help the reader understand what the intent is.

**Comment by bradh** [comment]
Maybe just link to https://www.sqlite.org/lang_expr.html#glob

More generally, constraints might benefit from an informative annex, or perhaps this could be in some separate "advanced geopackage" example-heavy tutorial.

**Comment by jyutzler** [comment]
In today's SWG we agreed that referencing the SQLite page was sufficient.

This issue will be closed once the proper pull request is applied.

**Comment by jyutzler** [comment]
closed by #159
