### ISSUE TITLE
Description column for `gpkg_extensions`

### ISSUE THREAD

**Issue by bradh** [opengeospatial/geopackage#175]
The standard says "The definition column value in a `gpkg_extensions` row for those extensions SHALL contain the Annex name as a reference." 

Previously that contained something meaningful (e.g. RTree got you "GeoPackage 1.0 Specification Annex M" or something similar). Its now always the same annex, irrespective of which extension. 

What should be put into that column, noting the schema requires it to be non-null?

**Comment by jyutzler** [comment]
I don't think this is a big deal. If it was Annex M before, it is Annex F.3 now.

**Comment by jyutzler** [comment]
I did change the wording on that phrase in #177 https://github.com/jyutzler/geopackage/commit/4b9a5503d4e9e2dffb9c1840adcd5305ea6dd85a#diff-eecb655f68b144611a300638e6df27a3
