### ISSUE TITLE
Annex cross-references require update

### ISSUE THREAD

**Issue by bradh** [opengeospatial/geopackage#176]
There are numerous cross-referencing issues for Annexes, including the ATS and parts of the new Annex F content that still refer to old Annexes (e.g. Requirement 86).

**Comment by jyutzler** [comment]
I attempted to fix this with #177. It might not be perfect but it should be a lot better. I think there were also some stale references that had nothing to do with #132.

**Comment by pepijnve** [comment]
@jyutzler it might be worthwhile to make these real asciidoc cross-references. That way they should stay up to date as long as you use stable anchor ids (i.e., not the autogenerated ones). I started the process of doing that (things like tables and figures are already done for instance), but never got round to the ATS.

**Comment by jyutzler** [comment]
@pepijnve I hear you but it isn't a good use of my time to do all of these. My head hurts just trying to think of a convention to uniquely name each reference. (There are at least 100.) I may still do this, but literally if I have time to kill.
