### ISSUE TITLE
CurvePolygon should be abstract

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#178]
From @kryden
> Figure 2 – core geometry model diagram – I believe that the class “CurvePolygon” should be `<<abstract>>`.

Fixing this would also give us a chance to put the source files for the figures under version control where they belong. Only 3 of the 6 figures are currently in there.

**Comment by pepijnve** [comment]
I don't think that's correct. That diagram is taken from the SQL/MM spec where, iirc, CurvePolygon is an instantiable type. I don't have access to the spec anymore so can't double check.

**Comment by jyutzler** [comment]
I've asked @pdaisey to double-check.

**Comment by pdaisey** [comment]
As Pepijn said, the diagrams and definitions were taken from ISO/IEC 
13249-3.

In GeoPackage Clause 2.1.1:

A brief description of each geometry type is provided below. A more 
detailed description can be found in ISO 13249-3[12].

I just have the FDIS version of 13249-3.

In Clause 4.1 Geometry Types:

ST_Geometry, ST_Curve, and ST_Surface are not instantiable types. No 
constructor functions are
defined for these types.

ST_Point, ST_LineString, ST_CircularString, ST_CompoundCurve, 
ST_CurvePolygon, ST_Polygon,
ST_Triangle, ST_PolyhdrlSurface, ST_TIN, ST_GeomCollection, 
ST_MultiPoint, ST_MultiCurve,
ST_MultiLineString, ST_MultiSurface, and ST_MultiPolygon are 
instantiable and have constructor
functions.

In Clause 4.9 4.2.9 ST_CurvePolygon:

The ST_CurvePolygon type is a subtype of ST_Surface. The ST_CurvePolygon 
type is instantiable. An
ST_CurvePolygon value is a planar surface consisting of a single patch, 
defined by one exterior boundary
and zero or more interior boundaries. Each interior boundary defines a 
hole in the ST_CurvePolygon
value.

Per those definitions the diagram is correct to show ST_CurvePolygon as 
instantiable.

**Comment by KRyden** [comment]
Let’s leave it alone – references below indicate no issue with the existing diagram.

Thanks
Keith
