### ISSUE TITLE
Add new column for 12-063 WKT

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#190]
As noted by @bradh in http://lists.opengeospatial.org/pipermail/geopackage/2015-December/000189.html
The [current implementation](http://www.geopackage.org/spec/#extension_crs_wkt) for #137 is a breaking change. A non-breaking change would be to add a new column for the 12-063-based definition instead of forcing the implementer to break or guess what the intention is.
How about `definition_12_063` as a column name?

**Comment by jyutzler** [comment]
What about the spatial_ref_sys view from Appendix C (Table 17)? 
http://www.geopackage.org/spec/#_gpkg_spatial_ref_sys

**Comment by pepijnve** [comment]
Those SRS views exist for SQL schema level compatibility with the SRS tables from the Simple Features and SQL/MM specs. Since both of those still use the previous SRS WKT you can probably leave them untouched.

**Comment by jyutzler** [comment]
I like what I have in #192 much better than what we had before. However, I don't think it is appropriate for me to accept it unilaterally.

**Comment by pepijnve** [comment]
Reviewed quickly out of curiosity. It does indeed seem like a better way to implement this extension.

My only remark is on the making `definition` nullable. Perhaps it would be better to keep it not null and recommend that it is populated with as close an approximation of the CRS as the old WKT spec allows. Not sure if that's even possible in all cases in the first place though. It would also mean that 'legacy' clients would potentially process the data less accurately rather than not at all. Again I'm not sure which alternative is the better one here.

**Comment by bradh** [comment]
Concur on the nullable `definition`. Made an alternative suggestion (fill in as best as possible, but allow `undefined`, possibly with some trigger to make sure that the `definition` and `definition_12_xxx` columns aren't both null).

**Comment by trgn** [comment]
I'm in favor of this proposed change #192.

I guess it summarizes as (correct me if I missed anything crucial):
- use an extra column for the new WKT-standard
- do not introduce the null value in `definition`, as it violates earlier use
- use `undefined` in the manner outlined by @bradh in #192. ensure the values in `definition*` correspond to the established relationship with the `srs_id` value (0/-1)

@jyutzler wondered if this would prevent adoption of the new WKT spec. I don't feel strongly about this either way. 

The current proposal does reduce the urgency of implementers to support 12-063. But the Geopackage effort is not the only vehicle to drive adoption of new WKT standards.

I also understand it was the intention of gpkg to remain a single version specification. That does not exclude the possibility of later updates or amendments to the gpkg-spec to deprecate the old WKT standard. IMO, the current proposal - which is low impact - is OK as a first step in that transition.

**Comment by bradh** [comment]
I don't see it as a GeoPackage responsibility to drive 12-063. GeoPackage is supposed to be an "easy to implement, uses standard products as building blocks" standard. 

12-063 is going to be moderately hard to implement completely, and quite hard to get right for reprojection (because of the removal of the WGS84 conversion factors). We really don't want to be on the leading edge.

**Comment by cnreediii** [comment]
Brad -

If there is an issue with 12-063 that inhibits effective use, then I would suggest a discussion with Roger Lott and perhaps a change request to 12-063. As 12-063 is a joint OGC-ISO document, the OGC can suggest (and make changes). As a side note, given that 12-062 is an ISO standard, expect that document to begin appearing in procurement language in many countries as a mandatory must implement standard.

Regards

Carl

**Comment by bradh** [comment]
I think its pretty clear from the 12-063 text (see http://docs.opengeospatial.org/is/12-063r5/12-063r5.html#144 Section C3.3) that the SWG made a deliberate decision to remove it for modeling purity.

**Comment by pepijnve** [comment]
@bradh form what I remember from the single CRS meeting I attended that is indeed a deliberate decision. The TOWGS84 seven parameters aren't really an intrinsic part of a CRS' definition. It pushes implementers towards an early binding, hub and spoke style transformation system with WGS84 as the hub reference. In the new model you basically have to get those transformation parameters from somewhere else, like the EPSG database for instance. I agree with you that this is going to require a bit more work for people to implement and it's not easy for non-expert users to implement correctly.

Perhaps the 12-063 GeoPackage extension should also include a way to embed transformation parameters in the GeoPackage as well to ease adoption.
12-063 provides a syntax for coordinate operations (see http://docs.opengeospatial.org/is/12-063r5/12-063r5.html#113) which you can use to encode (among other things) datum transformations. A GeoPackage could include a separate gpkg_coordinate_transformation table that contains (source crs id, target crs id, coordinate operation wkt) tuples where the crs ids are foreign key references to the spatial reference table. A best practice could then be to include a 'target == wgs84' transformation for any non-wgs84 datums that a GeoPackage uses.
This retains the cleaner CRS modelling of 12-063, avoids encoding (potentially) duplicate transformation parameters in each CRS but still provides the convenience of the old CRS WKT model.

**Comment by jyutzler** [comment]
At today's SWG, we agreed to have two columns but to keep the original column mandatory. I will revise #192 and merge.
