### ISSUE TITLE
New converter "INTERLIS to GeoPackage" (country specific)

### ISSUE THREAD

**Issue by sfkeller** [opengeospatial/geopackage#198]
There's a new country specific converter for the Swiss national exchange format, called "INTERLIS 2-loader for GeoPackage" (ili2gpkg) [1][2]: Is it OK to make a pull request at gh-pages to add this to the software list?

[1] http://www.eisenhutinformatik.ch/interlis/ili2pg/
[2] https://github.com/claeis/ili2db/tree/master/ili2gpkg/src/ch/ehi/ili2gpkg

**Comment by jyutzler** [comment]
Yes, that's fine. We'll take a look. Please add this entry to the bottom of the list.

**Comment by jyutzler** [comment]
Merged #202
