### ISSUE TITLE
Branch protection prevents editorial fixes

### ISSUE THREAD

**Issue by bradh** [opengeospatial/geopackage#210]
It appears branch protection has been enabled. That has the undesired consequence of preventing people clicking on the edit icon and fixing a typo.

Please reconsider.

**Comment by jyutzler** [comment]
Branch detection is not enabled on this repository. From the settings:

```
Protected branches
Protect branches to disable force pushing, prevent branches from being deleted, and optionally require status checks before merging. New to protected branches? Learn more.

Choose a branch... 
No protected branches yet.
```

**Comment by bradh** [comment]
Must be a user error.
