### ISSUE TITLE
Problem with Table of Contents and Annexes

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#212]
On the spec page http://www.geopackage.org/spec/ the table of contents is cut off at annex F.7 and the headings are not showing up right after that point in the document.

**Comment by joegc** [comment]
It looks like a heading was left off of the extension_tiles_webp.adoc file but the ===== was there and creating a new table. I added "Extensions Mime Type" after the ===== to fix. I don't know if that is the correct wording so you may have to change it again.

**Comment by jyutzler** [comment]
Reopening this issue because it is still occurring on http://www.geopackage.org/spec110/

**Comment by jyutzler** [comment]
Fixed again. Not sure if it will recur.
