### ISSUE TITLE
Add "tile pyramid" to terms and definitions

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#213]
Does anyone have a suitable definition to add to Annex B.2?

**Comment by jyutzler** [comment]
Assigned to Luciad.

**Comment by fhoubie** [comment]
After internal discussions, what about reusing definition of tile matrix set from WMTS ?

**tile**
a rectangular pictorial representation of geographic data, often part of a set of such
elements, covering a spatially contiguous extent and sharing similar information content
and graphical styling, which can be uniquely defined by a pair of indices for the column
and row along with an identifier for the tile matrix.

**tile matrix**
a collection of tiles for a fixed scale

**tile matrix set**
a collection of tile matrices defined at different scales

**Comment by pepijnve** [comment]
that would make a lot of sense since the tiles part of the spec was (intentionally) modelled after WMTS.

**Comment by jyutzler** [comment]
:+1:
