### ISSUE TITLE
Lack of semantics for "last_change" in gpkg_contents

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#222]
The spec only mentions which formatting rules apply to the values of "last_change" in gpkg_contents but does not define its semantics. Is it the timestamp of the last change of the record in gpkg_contents itself (ie a change in identifier, description, min_x, max_x, min_y, max_y) or the timestamp of the latest change (insertion, update, delete) done in the table "table_name" ?

**Comment by jyutzler** [comment]
@rouault 
At today's SWG meeting we agreed in principle that `last_change` should be the change of the content of the referenced table. We acknowledge that it is unreasonable to make this a SHALL statement and plan to add a SHOULD statement to the spec. Does this sound reasonable to you?

**Comment by rouault** [comment]
Sounds good
