### ISSUE TITLE
Discrepancies between homepage, OGC page and spec

### ISSUE THREAD

**Issue by fnorf** [opengeospatial/geopackage#223]
http://www.geopackage.org/ says 

> The GeoPackage specification describes a set of conventions for storing the following within an SQLite database:
> 
> - vector features
> - tile matrix sets of imagery and raster maps at various scales
> - schema
> - metadata
> - extensions

http://www.opengeospatial.org/standards/geopackage says

> A GeoPackage is a platform-independent SQLite database file that may contain:
> 
> - vector geospatial features
> - tile matrix sets of imagery and raster maps at various scales
> - metadata

http://www.geopackage.org/spec/ lists Metadata and Schema as extensions:

> - http://www.geopackage.org/spec/#extension_metadata
> - http://www.geopackage.org/spec/#extension_schema

As this is confusing and misleading I would suggest harmonising the homepage with the OGC page and make sure to either not list the official extensions or mark them as such.

**Comment by jyutzler** [comment]
In progress. geopackage.org should be fixed by the time you read this. I'm looking into changing the bit on opengeospatial.org now.
