### ISSUE TITLE
gpkg_data_columns description column has incorrect description

### ISSUE THREAD

**Issue by cclark1984** [opengeospatial/geopackage#231]
In table 42, the gpkg_data_columns title column description reads "A human-readable formal title for the **column_name content**".

In table 42, the gpkg_data_columns description column description reads "A human-readable description for the **table_name content**".

I believe they should both read **column_name content**.

**Comment by cclark1984** [comment]
Created pull request 236 for this issue.

**Comment by jyutzler** [comment]
SWG has approved this change. PR to be accepted on 8/29.
