### ISSUE TITLE
Requirement 53 is Confusing.

### ISSUE THREAD

**Issue by cclark1984** [opengeospatial/geopackage#237]
The wording for Requirement 53 "The pixel_x_size and pixel_y_size column values for zoom_level column values in a gpkg_tile_matrix table sorted in ascending order SHALL be sorted in descending order." is confusing.

How about "When zoom_level column values in the gpkg_tile_matrix table are sorted in ascending order, the pixel_x_size and pixel_y_size column values in the gpkg_tile_matrix table SHALL appear sorted in descending order."

**Comment by cclark1984** [comment]
Updated in Pull Request 236.

**Comment by jyutzler** [comment]
SWG has approved this change. PR to be accepted on 8/29.
