### ISSUE TITLE
Document guidance for accessing GeoPackage over a network

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#247]
There was a discussion over email:
- http://lists.opengeospatial.org/pipermail/geopackage/2016-September/000198.html
- http://lists.opengeospatial.org/pipermail/geopackage/2016-October/000200.html

We should get this documented and put onto geopackage.org.

**Comment by rouault** [comment]
Note that the conclusions were slightly different after extra tests : https://lists.osgeo.org/pipermail/qgis-developer/2016-October/045075.html

**Comment by jyutzler** [comment]
Today we reviewed this and determined that since it is really an SQLite issue and not a GeoPackage issue that this is out of scope for us.
