### ISSUE TITLE
Register “GP11” with the SQLite group

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#253]
I didn't know that this was a thing we had to do. Anyone willing to do this, it would be greatly appreciated.

http://stackoverflow.com/questions/35557487/where-can-i-register-a-sqlite-application-id

**Comment by fhoubie** [comment]
Regarding this GP10/GP11/GP12 value, it is a bit strange because it breaks backward compatibility I think. Test 	/base/core/container/data/file_format/application_id will fail if you do not have the specific value.

**Comment by jyutzler** [comment]
This is overcome by #266
