### ISSUE TITLE
inconsistent use of min/max is inclusive

### ISSUE THREAD

**Issue by KRyden** [opengeospatial/geopackage#260]
At revision 1.1, the mixed case MinIsInclusive and MaxIsInclusive were changed to all lower case- the document now contains two different column references for each:

minisinclusive/min_is_inclusive
maxisinclusive/max_is_inclusive

This needs to be corrected - all lower case is the change that was to be made.

**Comment by jyutzler** [comment]
@KRyden I am only seeing minisinclusive in the abstract tests. That is a pretty easy fix. 
Do you see it anywhere else?

**Comment by KRyden** [comment]
That’s the only place I see it as well.  Simple editorial fix should suffice.

Keith
