### ISSUE TITLE
Remove Extended GeoPackage File Extension Recommendation

### ISSUE THREAD

**Issue by cclark1984** [opengeospatial/geopackage#261]
The OGC GeoPackage specification outlines in great detail the extension mechanism. In order for an application to determine what extensions are currently available, it must open the GeoPackage and query the gpkg_extensions table. It is likely that an application that supports no extensions can still access the GeoPackage without issue, especially if the application accesses a GeoPackage in a read-only fashion and the gpkg_extensions.scope column indicates a value of “write_only”. The presence of the ".gpkx" extension provides no real value. Applications still need to open the GeoPackage to determine if the extensions impose any additional requirements on accessing the data and therefore the ".gpkx" extension serves no purpose.

Applications will need to recognize two separate file extensions. There is a distinct possibility that application developers will only support the mandatory ".gpkg" file extension.

**Comment by jyutzler** [comment]
As we discussed during the SWG today, we will remove this option as it serves no discernible purpose.

**Comment by jyutzler** [comment]
http://ogc.standardstracker.org/show_request.cgi?id=392
