### ISSUE TITLE
Remove Minimal Set Of Rows From gpkg_spatial_ref_sys Table

### ISSUE THREAD

**Issue by cclark1984** [opengeospatial/geopackage#262]
Requirement 11 in the GeoPackage specification provides a minimal listing of rows that shall be contained in the gpkg_spatial_ref_sys table. These rows may not be necessary for the content of the GeoPackage and should not be required. They cause issues for possible profiles of the GeoPackage specification because these profiles may restrict the allowed CRSs, this restriction may not include EPSG:4326. Furthermore, since the allowed CRSs are defined, the value of srs_id of -1 for undefined Cartesian coordinate reference systems and the srs_id of 0 for undefined geographic coordinate reference systems will never be required. It is our recommendation to update this requirement so that the gpkg_spatial_ref_sys table MAY contain these entries.

**Comment by jyutzler** [comment]
Having a preset group of CRSs does improve interoperability because users, when in doubt, will use one of the predefined ones. I believe this is justification enough to leave things how they are.

Meanwhile I don't think this is a significant issue for profile users. I don't think it is appropriate to use gpkg_spatial_ref_sys as a whitelist for CRSs that are allowed by a profile.

**Comment by jyutzler** [comment]
http://ogc.standardstracker.org/show_request.cgi?id=393

**Comment by jyutzler** [comment]
We discussed this during the last SWG meeting but ran out of time before reaching a consensus. One item of note is that there are technical reasons to allow rows in the table even if they were not ultimately used. It is not unreasonable for an application to add data to a GeoPackage with a default CRS and go back to update it later. (Sometimes when doing RDBMS development you get tied in a knot and end up having to do something like this.)

There seems to be interest in:
* loosening the SHALL requirement
* stipulating that a GeoPackage MAY contain rows that are unused or even prohibited by a profile
* stipulating that a GeoPackage SHOULD contain default CRS rows to make things easier for developers with limited knowledge of CRSs

**Comment by jyutzler** [comment]
We've discussed this topic in two consecutive SWG meetings and we have not reached consensus that this is a necessary change. Some comments:
* "no direct benefit"
* "muddies waters"
* "willy-nilly"

Since no motion was raised, I am closing the issue.
