### ISSUE TITLE
Identification of Geopackage and Geopackage version in SQLite header

### ISSUE THREAD

**Issue by KRyden** [opengeospatial/geopackage#266]
In putting together a request for the SQLite team to give us additional Application IDs ("GP11", "GP12"), I came across another field in the header that is probably better for our usage – user_version.

Background – 

When Geopackage was first put together, the question was asked, “how do we tell it’s a geopackage”?  The answer Paul and others came up with was to use the application_id property described as follows:

PRAGMA schema.application_id; 
PRAGMA schema.application_id = integer ; 
The application_id PRAGMA is used to query or set the 32-bit unsigned big-endian "Application ID" integer located at offset 68 into the database header. Applications that use SQLite as their application file-format should set the Application ID integer to a unique integer so that utilities such as file(1) can determine the specific file type rather than just reporting "SQLite3 Database". A list of assigned application IDs can be seen by consulting the magic.txt file in the SQLite source repository. 
See also the user_version pragma. 

The description is pretty self-explanatory, and the initial application_id value was encoded with the version number as well… that appears to have been incomplete – as the header also provides a user_version field (keep in mind that in this context, the geopackage specification is the user).

PRAGMA schema.user_version; 
PRAGMA schema.user_version = integer ; 
The user_version pragma will to get or set the value of the user-version integer at offset 60 in the database header. The user-version is an integer that is available to applications to use however they want. SQLite makes no use of the user-version itself. 
See also the application_id pragma and schema_version pragma. 

See https://www.sqlite.org/pragma.html for the full documentation

Instead of updating the application_id each time we do a major or minor geopackage specification update, we should probably hold the application_id constant (“hello world, this is a Geopackage”), and update the user_version with the specification version the Geopackage corresponds to.  Following this logic then, we’d update requirement 2 to set the application_id, and the specification version number – the application_id would be a constant, and the user_version would be set to the geopackage specification version number.

We could retain the existing application_id of “GP10” for compatibility, and  if there was ever a truly massive specification change, we’d have the option of updating the application_ID.

We would then need a user_version integer schema.  I would suggest three digit major, two digit minor, two digit bug-fix:
1.0=0010000
1.0.1=0010001
1.0.2= 0010002
1.1= 0010100
1.2=0010200

Using this approach, we don’t have to update anything with SQLite when we publish specification changes.  Identification of a geopackage is separated from identification of the geopackage specification revision number.  And the granularity of the revision number allows us to be as fine-grained or coarse-grained as we wish.

Other than the fact that the Geopackage 1.1 specification is already published – what are your thoughts on this? I’d be game to go this route and issue an update to 1.1 before it gets wider adoption – it makes things much cleaner.

If we went this route, Requirement 2 could be changed as follows (the note on earlier geopackage versions is suggested for backward compatibility):

"A GeoPackage SHALL contain 0x47503130 ("GP10" in ASCII) in the application_id field of the SQLite database header to indicate a GeoPackage data file.  The GeoPackage specification version SHALL be identified by an integer value of "0010100" in the user_version field of the SQLite database header. A value of 0 or NULL in the user_version field MAY be an indication of an earlier version 1.0 or 1.01 GeoPackage"

**Comment by KRyden** [comment]
A quick experiment shows that the user_version field value is always returned as 0 if it has not been set.  In addition, we probably need to add the explicit version number as it's formatted for the document to avoid any confusion.  That would lead to Requirement #2 reading something like this:

"A GeoPackage SHALL contain 0x47503130 ("GP10" in ASCII) in the application_id field of the SQLite database header to indicate a GeoPackage data file. The GeoPackage 1.1 specification SHALL be identified by an integer value of "0010100" in the user_version field of the SQLite database header. A value of 0 in the user_version field MAY be an indication of the version not being properly set, or an earlier version 1.0 or 1.01 GeoPackage"

**Comment by KRyden** [comment]
closed in error -

**Comment by pepijnve** [comment]
@KRyden are you sure this is a good idea? Applications may be using the user_version field for other things already (e.g. change tracking). By assigning a predefined meaning to the field in the geopackage spec you might end up causing problems for existing applications.
Why not change the required application id value whenever an incompatible change happens in the spec? You don't have to sync that with the sqlite team if you don't want to.
Note that the application id value was always intended to be a hint rather than a strict requirement. Older versions of sqlite don't support reading and writing this value so it may not be possible for all applications to populate this in the first place.

**Comment by cclark1984** [comment]
I would recommend changing the application_id to be 0x47504b47 ("GPKG" in ASCII) and already in the  magic.txt. (Doesn't reference 1.0 version like the other)

I like the idea of using the user_version field, keep in mind when you query the version "0010100" you will probably just get 10100.
