### ISSUE TITLE
Links to References within footnotes

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#317]
In a number of places we have links to [Normative References](http://www.geopackage.org/spec/#_normative_references_normative) within footnotes. In general, you link to a Normative Reference by putting something like <<8>> in the text. However, in our footnotes, none of the links work. Look in footnote 6 here:
https://github.com/opengeospatial/geopackage/blob/master/spec/1_base.adoc#_footnote_6
If you look at the [footnotes](http://www.geopackage.org/spec/#_footnote_1), there are a large number of broken references.

**Comment by ogcscotts** [comment]
The references do link when the full doc is processed. Because the references are "downstream" of this section, links will not resolve without the entire standard compiled.

**Comment by jyutzler** [comment]
@ogcscotts We'll take a look at the new version once it is recompiled. Hopefully the issue has gone away.

**Comment by ogcscotts** [comment]
OK, the fully compiled version (generated from Asciidoctor) has working links in footnotes. The version created from GitHub Pages still does not.  Looking for a workaround.

**Comment by jyutzler** [comment]
Fixed as part of final release of 1.2
