### ISSUE TITLE
Clarify case sensitivity of data types

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#339]
In a number of places, including but not limited to [Requirement 5](http://www.geopackage.org/spec/#r5), we specify required and/or allowed SQLite data types. In the text and tables these are always UPPERCASE. However, I am finding GeoPackages with lowercase data types. This does not seem to cause SQLite any problems but the tests as currently written are failing. 

1. We need to clarify whether GeoPackage data types must be UPPERCASE or if they are case insensitive.
1. We must decide how rigid the tests must be and whether it this is based on the version. If necessary, the strictness of the test can vary by GeoPackage version.

**Comment by rcasscslt** [comment]
I am voting for case insensitive as sqlite does not care. I am all for back-porting case insensitivity to the test suite for 1.1 as well. I am not sure of a case where a client would expect a particular case when processing the schema of core tables. Are there built in constraints in core GPKG SQL that require UPPERCASE?

**Comment by jyutzler** [comment]
It makes me wonder why those stipulations were put there in the first place. If the group agrees that case-insensitive is the way to go, I will go back and scrub the ETS. Scrubbing the requirements will be more annoying but I can be talked into that if needed.

**Comment by jyutzler** [comment]
We're not going to change the requirements here, but I will modify the ETS to allow case-insensitive checks in places where case-sensitivity will not affect SQLite. Really the only time SQLite cares about case is in text strings.
