### ISSUE TITLE
Replace Whitehorse sample

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#340]
Reference: https://lists.opengeospatial.org/mailman/private/geopackage.swg/2017-January/001579.html

Note that we don't currently have a way to test the veracity of the coordinate reference system definitions stored in `gpkg_coord_ref_sys`.

**Comment by jyutzler** [comment]
We temporarily removed this sample from geopackage.org. We still need to find someone to review the CRS.

**Comment by davidstategicaci** [comment]
I was unable to find the source raster to determine if the issue started at the source. However, the GPKG standard has evolved so i recommend replacing with with a set of raster, vector, and NSG style geopackage examples.

**Comment by jyutzler** [comment]
Works for me.

**Comment by jyutzler** [comment]
Fixed by @davidstategicaci 
I have updated the [samples page](http://www.geopackage.org/#sampledata).
