### ISSUE TITLE
Inconsistency between "Table 10. Tiles Table or View Definition" and C.7. sample_tile_pyramid 

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#358]
[Table 10](http://www.geopackage.org/spec/#example_tiles_table_cols) mentions that 0 should be used as default value for zoom_level, tile_column and tile_row, but [Annex C.7](http://www.geopackage.org/spec/#example_tiles_table_sql) does not have "DEFAULT 0" in the DDL.

A default value for records in a tile pyramid table doesn't make sense to me, so I think the example is right.

/opt/tiles/tile_pyramid/data/table_def only tests the existence of those columns, and not their type, not null constraint or default values.

**Comment by jyutzler** [comment]
In the SWG meeting yesterday, we agreed to accept this change. It will be included as part of 1.2.
