### ISSUE TITLE
Reword Requirement #92

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#362]
Requirement 92 is currently unclear. 

> (extends GPKG-36 and GPKG-37) A GeoPackage that contains a tile pyramid user data table that contains tile data MAY store tile_data in MIME type image/x-webp [22]. The MIME type of values of the tile_data column in tile pyramid user data tables SHALL be image/x-webp.

Does this mean that you can have PNG or JPG tiles or not? The first sentence suggests you can, the second suggests you can't. I believe that the first sentence matches the spirit and intent of the requirement. A better wording might be:

> (extends GPKG-36 and GPKG-37) A GeoPackage that contains a tile pyramid user data table that contains tile data MAY store tile_data in the WebP format [22]. Files complying with the WebP format SHALL have the MIME type of image/x-webp.

Ref: https://github.com/opengeospatial/ets-gpkg12/issues/11
h/t @rouault

**Comment by rouault** [comment]
> Files complying with the WebP format SHALL have the MIME type of image/x-webp.

Tiles rather than files ? But I don't understand what this sentence brings. Saying that tile_data may be in the WebP format is that same than saying that the MIME type is image/x-webp.
