### ISSUE TITLE
Support for TWKB or other compact geometry encoding

### ISSUE THREAD

**Issue by spatialillusions** [opengeospatial/geopackage#365]
The vector data in geopackage is today encoded as WKB, a well-defined and well known way of formatting spatial geometries.

However, since all coordinates are encoded as two 64bit double values, they will be quite large when stored in a geopackage. One way to solve this is to simplify the geometries and simply remove coordinates that are considered unnecessary at a specified scale. (It is possible to store a geodetic arc degree with a precision better than 1mm with half the number of bits. See [NGA.STND.0019_2.0]( http://earth-info.nga.mil/GandG/wgs84/web_mercator/(U)%20NGA.STND.0019.2.0%20Time%20Space%20Position%20Information%2005Apr2012.pdf))

Another way to solve the problem is to use [TWKB](https://github.com/TWKB/Specification/blob/master/twkb.md) as the geometry encoding. 
https://github.com/TWKB/Specification

>TWKB is a multi-purpose format for serializing vector geometry data into a byte buffer, with an emphasis on minimizing size of the buffer.

This format is relatively new compared to WKB since it just been around a few years, but is implemented in several systems where the size of geospatial data matters.
https://carto.com/blog/smaller-faster
It has native support in PostGIS and there are several open implementations in different languages for reading TWKB.

One way to be able to encode the geometries as TWKB in geopackage would have been to use F.2, but that has now been removed in #235. And I cannot see any other ways to support different geometry encodings in geopackage.

So my question now is if there are any plans to have the possibility to store coordinates more compact than today, or if WKB will be the only option for encoding geometries?

**Comment by jyutzler** [comment]
At this time there are no plans to support an encoding other than WKB. Furthermore, as this issue transcends GeoPackage (and applies across the Simple Features spectrum), it really needs to be taken up at a higher level. If OGC gets behind TWKB, GeoPackage will probably fall in line. I will contact the chair of the OGC Simple Features working group and let him know that interest is out there.

However, nothing is preventing you from developing a proprietary extension if you feel that is necessary to meet a mission need.
