### ISSUE TITLE
Case sensitivity of values in table_name in gpkg_extensions is not explicit. Should it be?

### ISSUE THREAD

**Issue by rcasscslt** [opengeospatial/geopackage#375]
[The gpkg_extensions table definition](http://www.geopackage.org/spec/#extensions_table_definition) does not explicitly indicate the case requirements for values in the table_name column. 

Consider that table names are case-insensitive in SQLite when doing standard queries, also at least one well-known sqlite package automatically lower-cases table names when it registers its GeoPackage extensions.

Is the default to be case-insensitive or insensitive?

At least two tests : 

- /opt/extension_mechanism/data/data_values_table_name
- /opt/extension_mechanism/data/data_values_column_name

are using a case-sensitive string comparison of the table_name column and the name column in sqlite_master. 

Should the table_name column definition explicitly define case requirements? What are the implications?

**Comment by jyutzler** [comment]
At the SWG meeting yesterday we agreed to change the executable test (and abstract test, if necessary) to make the queries case-insensitive since SQLite table names are case insensitive.

**Comment by jyutzler** [comment]
The ETS actually had some clever code to determine if a default was functionally equivalent to the spec. Unfortunately, this can't work on dates because of the milliseconds that pass between one call to "current_timestamp" and the next. I had to add a special case.

fixed as part of https://github.com/opengeospatial/ets-gpkg12/pull/14

**Comment by jyutzler** [comment]
I think I have a fix for this as part of https://github.com/jyutzler/ets-gpkg12/commit/ea4c7e170dbd4628b5b27812c9f1638069d0263b
Waiting confirmation.

**Comment by jyutzler** [comment]
This does cause an administrative change to the specification.
