### ISSUE TITLE
What is proper geopackage mediatype and why is it not registered at IANA 

### ISSUE THREAD

**Issue by pvgenuchten** [opengeospatial/geopackage#381]
Hi all, I wondered about this before but never got around to create an issue. What is the proper media/mimetype for geopackage? I noticed some use application/x-sqlite3, which may work but is less optimal. 

On top of that neither gpkg as x-sqlite3 are registered at Iana (https://www.iana.org/assignments/media-types/media-types.xhtml), which seems the most obvious place to register this type of conventions. I Noticed some OGC mediatypes are listed, are those initiatives of individuals (Scott for geoxacml/Clemens for gml/google for KML).

In the catalogue domain we typically embed a mediatype in the metadata for any spatial file, these mediatypes are preferably taken from common codelists. Within INSPIRE this codelist is used:  http://inspire.ec.europa.eu/media-types/application. This codelist uses uri's from iana, where available. the list currently doesn't list the geopackage mediatype, i want to notify them, but would love to give them some indication of a uri to use.

see also this list https://www.w3.org/2015/spatial/wiki/BP_SpatialDataFormats (with missing mediatype for gpkg)

**Comment by jyutzler** [comment]
Since GeoPackage is effectively just an SQLite database, the `application/x-sqlite3` is commonly used. This MIME type is not allowed to be registered at Iana. I don't know why the SQLite people haven't produced a proper MIME type but this isn't really up to us.

**Comment by pvgenuchten** [comment]
Seems the sqlite team is looking for volunteers to manage about their registration at iana
http://sqlite.1065341.n5.nabble.com/Why-is-Sqlite-mediatype-not-registered-at-iana-td97088.html

but also some fundamental thoughts on that thread, should sqlite be registered as a structured syntax suffix (RFC 6839) or a file with a mediatype (in my use cases it is mostly the latter)

**Comment by pvgenuchten** [comment]
Again some activity at the sqlite group related to this activity, seems the media type suggested is 
application/vnd.sqlite3

http://sqlite.1065341.n5.nabble.com/Re-Why-is-Sqlite-mediatype-not-registered-at-iana-td97826.html

**Comment by cladisch** [comment]
SQLite now has a registered media type, and a structured syntax suffix.

The GeoPackage media type should be registered as something like `application/vnd.opengeospatial.geopackage+sqlite3`.

**Comment by jyutzler** [comment]
@cladisch Do you have something we can cite for this change?

**Comment by cladisch** [comment]
https://www.iana.org/assignments/media-types/media-types.xhtml
https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml

**Comment by jyutzler** [comment]
Very helpful, thanks. I will create a change for the next version.

**Comment by jyutzler** [comment]
I have reached out to OGC staff to figure out exactly what we need to do to get GeoPackage registered properly.

**Comment by jyutzler** [comment]
We now have confirmation for IANA: `application/geopackage+vnd.sqlite3`
https://www.iana.org/assignments/media-types/media-types.xhtml

I'm leaving this open until I can update geopackage.org and the working version of the standard.
