### ISSUE TITLE
Wrong DDL for gpkg_metadata table in "Hierarchical Metadata Example One - ISO19115" annex

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#382]
https://github.com/opengeospatial/geopackage/blob/master/spec/annexes/metadataexample.adoc contains a wrong version of the DDL of CREATE TABLE gpkg_metadata : wrong default value for md_scope and metadata columns, and even more annoying, missing mime_type column.

2 options :
* correct this DDL
* or perhaps better, remove it to avoid duplication of information and source of errors. If doing so, the "CREATE TABLE gpkg_metadata_reference" DDL a bit below should be removed for consistency

**Comment by jyutzler** [comment]
Thanks for this. We just need to figure out where it will live on-line.

**Comment by jyutzler** [comment]
geopackage.org/spec now points to the working version
geopackage.org/spec120 is a permalink to the released version
Now both are linked from geopackage.org
