### ISSUE TITLE
17-066r1 Tile gridded coverage data: inconsistant default value for grid_cell_encoding in "Table 1: Coverage Ancillary Table Definition"

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#384]
Table 1 mentions that the default value of grid_cell_encoding is 1, but "7.1.1.2 grid cell encoding" mentions 3 possible text values. So the default should likely be 'grid-value-is-center' instead of 1

**Comment by cnreediii** [comment]
Corrected. Thanks.
