### ISSUE TITLE
17-066r1 Tile gridded coverage data: confusing "7.1.1.4 field_name"

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#385]
* "each “field” attribute in a given instance shall be identified by a name that is unique to this instance" --> what does instance mean in that context ? A GeoPackage database ?
* "In the case of this extension, the there is only one field attribute and one instance" : typo 'the' before 'there' should be removed
* "For example, a specific grid coverage is comprised of “heights”, temperatures, or pressures": I believe this sentence could/should be removed. Generally when you mention an example, you mention something valid for the context of what you talk about. Here it is a counter exemple. And when reading quickly one assumes that it relates to the XML snippet just below, which in fact has only one field
* It is probably obvious, but given the above sources of confusion, it wouldn't hurt that the value for the GeoPackage 'field_name' column should be the swe:field@name attribute, so here "temperature". In my first reading, I was wondering if it shouldn't this whole XML snippet

**Comment by cnreediii** [comment]
Evan - Working on your first bullet. Will pass new wording by you when done. Second bullet: Corrected. Third bullet: re-wrote a couple of sentences. Example and text now correspond. Fourth bullet: I think the SWG may need to discuss this one a bit more.

**Comment by cnreediii** [comment]
Finally re-wrote the clause. Indeed, the wording was confusing. Basically, the clause should state that a gridded coverage instance can only be one phenomenon as defined in the OGC/ISO standards baseline:  A physical property that can be observed and measured, such as temperature, gravity, chemical concentration, orientation, number-of-individuals.
