### ISSUE TITLE
17-066r1 Tile gridded coverage data: lack of normalization for 'uom'

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#386]
"7.1.1.3 uom" doesn't give much guidance on the values that can put there
Let be down to eath: for elevations, what is the value to put there for meters or feet ?

**Comment by cnreediii** [comment]
Even -

Could you provide a bit more information? In the SWG call today, we were not quite sure of the best approach to address your comment. In the OGC, most standards that have specific clauses related to UoM typically reference UCUM as the normative vocabulary. Of course, there are others! That said, we did add the UCUM reference to Section 3 - References. As to how to actually specify the UoM, that is a good point. I have added some UCUM examples. However, there is still the issue of how does an application know what authoritive reference is being used for the UoM.

Thanks

**Comment by rouault** [comment]
I don't have much suggestion. I was just pointing the fact currently this was mostly a free text field, and thus could cause interoperability issues. Pointing to UCUM seems to be a good move.

**Comment by ghobona** [comment]
The O&M standard uses OGC URNs to state the units of measurement used in the data.
Some examples from Annex C of OGC 10-025r1  are below.

urn:ogc:def:UCUM::m

urn:ogc:def:uom:UCUM:1

Please consider using URNs as example values in Section 7.1.1.3 of the draft GeoPackage extension (17-066r1).

**Comment by cnreediii** [comment]
I have expanded the UoM section to provide guidance but also be a bit general in recognition that the OGC is just now beginning to address the need for a formal cross standard mechanism for UoM specification as well as (perhaps) an official OGC registry of UoM resources.
