### ISSUE TITLE
Tile gridded coverage data: NaN not supported for data_null

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#388]
I don't think there is really something actionable about that, but just wanted to mention that not-a-number / NaN is a popular null value for Float datasets, so users might be tempted to use it, but SQLite3 doesn't support writing NaN in a Real column. Perhaps adding a note about that in the spec ?

What triggers this issue is this email from a GDAL user:
https://lists.osgeo.org/pipermail/gdal-dev/2017-September/047262.html

**Comment by jyutzler** [comment]
I thought we had something here but I can't find it so maybe it was dropped accidentally. The whole point for `data_null` was to prevent people from using NaN, -32767, etc. 

We will correct this.

**Comment by rouault** [comment]
> the whole point for data_null was to prevent people from using NaN, -32767, etc.

Not sure to understand what you mean. a nodata value is generally sent to a unlikely value like -32767. I don't see how data_null would be different from that

**Comment by jyutzler** [comment]
You're right, I wasn't thinking clearly when I wrote my reply.

**Comment by jyutzler** [comment]
This is covered by Requirement #143.

`All pixels in an elevation tile SHALL be set with a valid component value. The
mechanisms defined in this extension SHALL be used to indicate a missing value for a
pixel. Use the data_null value defined in Coverage Ancillary.`

We will update the requirement to be explicit about not using NaN. How about a simple `Special floating point values such as NaN and Inf SHALL NOT be used.`?

**Comment by rouault** [comment]
> How about a simple Special floating point values such as NaN and Inf SHALL NOT be used.?

Fine for me. Actually only NaN is a true issue with sqlite3. You can insert and retrieve positive or negative infinity just fine, but it is probably pushing sqlite3 capabilities at their limit

**Comment by cnreediii** [comment]
Text has been updated in requirement 21 (was 143).
