### ISSUE TITLE
Tiled Gridded Coverage Data extension_name missing author

### ISSUE THREAD

**Issue by bosborn** [opengeospatial/geopackage#399]
The new Tiled Gridded Coverage Data `extension_name` of ["2d_gridded_coverage"](http://www.geopackage.org/17-066r1.html#gpkg_extensions) is missing an author.  Was the author prefix of `gpkg_` mistakenly left off?  This appears to violate [requirement 62](http://www.geopackage.org/spec120/#_extensions) and deviates from [other registered extensions](http://www.geopackage.org/spec120/#registered_extensions).

**Comment by jyutzler** [comment]
@bosborn 
We were running into a chicken and egg problem - people were using draft extensions with the gpkg_ prefix before they were adopted and then they were changed, causing confusion. The convention is now to not use the prefix on draft extensions, but to assign an alias once the extension is adopted by OGC. 

We have done this here:
https://github.com/jyutzler/geopackage-related-tables/blob/master/spec/1_related_tables.adoc#extension-name-or-template

I suppose I should update the text in the Tiled Gridded Coverage extension as well.

**Comment by bosborn** [comment]
OK, thanks.  I also just noticed the Tiled Gridded Coverage Data iii. Preface still uses the previous extension name: `gpkg_elevation_tiles`

So are we going with `2d_gridded_coverage` and then `gpkg_2d_gridded_coverage` when adopted?  Or sticking with `elevation_tiles` and then `gpkg_elevation_tiles` when adopted?  A combination?  Or currently unknown?

**Comment by jyutzler** [comment]
The former.

The preface needs to be fixed. Thanks for bringing that to my attention.

**Comment by jyutzler** [comment]
Fixed by https://github.com/opengeospatial/geopackage-tiled-gridded-coverage/pull/38/files
Please confirm and I will close.

**Comment by bosborn** [comment]
Looks good to me, thanks!
