### ISSUE TITLE
Tiled Gridded Coverage Data gpkg_2d_gridded_coverage_ancillary SQL

### ISSUE THREAD

**Issue by bosborn** [opengeospatial/geopackage#400]
Update the SQL in [gpkg_2d_gridded_coverage_ancillary](http://www.geopackage.org/17-066r1.html#_coverage_ancillary_table_definition_sql)

Replace: `grid_cell_encoding TEXT (DEFAULT grid-value-is-center)`

with: `grid_cell_encoding TEXT DEFAULT 'grid-value-is-center'`

**Comment by jyutzler** [comment]
Fixed by https://github.com/opengeospatial/geopackage-tiled-gridded-coverage/pull/38/files
Please confirm and I will close.

**Comment by bosborn** [comment]
Looks good to me, thanks!
