### ISSUE TITLE
Geometry Encoding Clarification for Non-Linear Geometry Types

### ISSUE THREAD

**Issue by bosborn** [opengeospatial/geopackage#402]
Do the [non-linear geometry type](http://www.geopackage.org/spec120/#extension_geometry_types) extension [codes](http://www.geopackage.org/spec120/#geometry_types_extension) result in a [GeoPackageBinary type bit](http://www.geopackage.org/spec120/#gpb_format) of 0 (StandardGeoPackageBinary) or 1 (ExtendedGeoPackageBinary)?

It is validated to always be 0 [in ets-gpkg12](https://github.com/opengeospatial/ets-gpkg12/blob/b472ead81c2bac132ac193efb030052f8b2b3636/src/main/java/org/opengis/cite/gpkg12/features/FeaturesTests.java#L156).  Was this bit only meant to be 1 for the deprecated user defined geometry types?  It's a little confusing that the non-linear geometry types require an extension but are encoded with an extended bit of 0 (StandardGeoPackageBinary) instead of 1 (ExtendedGeoPackageBinary).

**Comment by jyutzler** [comment]
Yeah it is a little confusing. I think that anything on [this list](http://www.geopackage.org/spec120/#geometry_types) gets a 0 and anything for the deprecated extension gets a 1. I'm going to leave this open until I can get someone else to confirm.

**Comment by pepijnve** [comment]
I'm not sure what the intention was for this either anymore. The idea of the extension bit was that it provided an indication that the geometry body was not encoded in standard WKB. Instead it started with a vendor tag followed by vendor specific content.
The non-linear geometry types are still encoded in standard WKB, so *not* setting the extended flag seems like the correct thing to do.

**Comment by jyutzler** [comment]
closed by #404
