### ISSUE TITLE
Add favicon to pages on geopackage.org

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#403]

**Comment by jyutzler** [comment]
@gbuehler We appear to have the favicon available on most pages, but not the spec pages which are automatically generated. Can you guys add this in on your side?

**Comment by ogcportal** [comment]
We have updated the static versions of the specs.  The working draft cannot currently be fixed as it uses an old version of asciidoctor in the travis build.  Newer versions of asciidoctor allow for the inclusion of the favicon attribute node in asciidoc.
