### ISSUE TITLE
Versioning of extensions

### ISSUE THREAD

**Issue by bradh** [opengeospatial/geopackage#405]
_From discussion on related tables extension:_

It should be possible to version extensions (e.g. to extend them, or make breaking updates). Right now, the only way to do this is to embed the version in the `extension_name` somehow - effectively that it is a different extension - which may not make sense for an up-rev that isn't really breaking.

**Comment by jyutzler** [comment]
We discussed this during the SWG today and I proposed adding a column to `gpkg_extensions`, but there didn't seem to be a sense of urgency for addressing this. I'll propose a PR to this effect but it might stay out there for a while.

**Comment by jyutzler** [comment]
Closing this as WONT FIX
