### ISSUE TITLE
GeoPackage Port au Prince Sample Data Issue

### ISSUE THREAD

**Issue by bosborn** [opengeospatial/geopackage#406]
The [Port au Prince, Haiti Sample Data GeoPackage](https://portal.opengeospatial.org/files/?artifact_id=74863)(446.36 MB) listed under [GeoPackage Sample Data](http://www.geopackage.org/#sampledata) does not contain correct feature SRS values.

The srs_id for all values in the gpkg_geometry_columns table is 3395 (World Mercator).  The geometries appear to be specified in 4326 (WGS84).  The gpkg_contents srs_id values for the features are in 4326.  This also violates the soft srs_id matching requirement as discussed in #233.  As far as I can tell this "requirement" to have duplicate foreign keys match is still only specified in the description column of the [Contents Table Definition](http://www.geopackage.org/spec120/#_contents).

This sample data GeoPackage can be fixed by running the SQL:
`update gpkg_geometry_columns set srs_id = 4326`

**Comment by jyutzler** [comment]
Thanks, @bosborn.
@rcasscslt can you take a look at this?

**Comment by rcasscslt** [comment]
Will do

**Comment by jyutzler** [comment]
@bosborn Compusult has uploaded a new version (same URL). Please check it out.

**Comment by bosborn** [comment]
Thanks!  Can we change the permissions [on the file](https://portal.opengeospatial.org/files/?artifact_id=74863)?  Clicking on the link asked me to login and after logging in, I still didn't have access.

**Comment by jyutzler** [comment]
@bosborn Try it now please.

**Comment by bosborn** [comment]
Looks good to me and is functioning correctly, thanks!

**Comment by jyutzler** [comment]
Great! Thanks for checking it out.
