### ISSUE TITLE
CITE Test error - tiles data table schema test

### ISSUE THREAD

**Issue by KRyden** [opengeospatial/geopackage#412]
The CITE Test for validation of the schema of the tiles data table is not properly testing the NOT NULL property of the ID column.  The ID column is declared NOT NULL being TRUE in the spec - the test is checking for NOT NULL being FALSE - returning the following test error:
	 
Tiles Table Definitions
java.lang.AssertionError: Tile pyramid user data table q0513ne does not conform to the correct definition: Required column id is defined as: Type: INTEGER, not null: true, default value: null, primary key: true, unique: true but should be: Type: INTEGER, not null: false, default value: null, primary key: true, unique: true

A screen shot of a table with SCHEMA and CITE reported error below:

![cite test error for tiles table schema](https://user-images.githubusercontent.com/2131460/37313629-fe8de752-2647-11e8-9417-cbed6c08b8f1.png)

**Comment by jyutzler** [comment]
Can we get ahold of the test file? That would help.
