### ISSUE TITLE
UPDATE3 Trigger needs to be reviewed

### ISSUE THREAD

**Issue by KRyden** [opengeospatial/geopackage#414]
The update3 trigger needs to have the “of <c>” portion (in yellow below) struck.  As written the update3 trigger will only fire when the geometry is actually updated because of the “of <c>” clause – the key action this trigger is designed to handle is when the ID is changed – it can also deal with a geometry change at the same time – but as written will not fire if only the ID is changed.

This has not surfaced in the field because most SQLite applications never change the internal id value of an existing row. This would be hard to debug in the field…

![update3 trigger logic problem](https://user-images.githubusercontent.com/2131460/37315022-4022f34a-264f-11e8-806f-c2bae8086d5d.png)

**Comment by jyutzler** [comment]
@rouault What do you think?

**Comment by jyutzler** [comment]
If we confirm this is an issue, this would be a good reason to issue a GeoPackage corrigendum. The ETS would be updated so that 1.2.0 and older work on either version of the trigger and 1.2.1 and later require the updated version.
