### ISSUE TITLE
Is 'http://www.geopackage.org/spec/#extension_tiled_gridded_elevation_data' valid ?

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#417]
The table http://docs.opengeospatial.org/is/17-066r1/17-066r1.html#requirement_6 mentions 'http://www.geopackage.org/spec/#extension_tiled_gridded_elevation_data' as the value of the definition to put in the gpkg_extensions table. This was the value used for the intermediate version of the extension. There is a footnote 13 : http://docs.opengeospatial.org/is/17-066r1/17-066r1.html#_ftn13 that says "Need to change this and the two above to this document.", so it looks like another value was thought...

**Comment by rouault** [comment]
OK I see in the master doc https://github.com/opengeospatial/geopackage-tiled-gridded-coverage/blob/master/standard/clause_7_normative_text.adoc that this was changed to TBD and that it should probably point to http://docs.opengeospatial.org/is/17-066r1/17-066r1.html?

**Comment by jyutzler** [comment]
Please confirm that https://github.com/opengeospatial/geopackage-tiled-gridded-coverage/pull/40 fixes this.

**Comment by rouault** [comment]
> Please confirm that opengeospatial/geopackage-tiled-gridded-coverage#40 fixes this. Meanwhile I'm trying to get the file regenerated.

Looks good to me. I actually noted that the extension_name is changed to be prefixed by gpkg_

**Comment by rouault** [comment]
@jyutzler  FYI, support for 17-066r1 has been added in GDAL 2.3.0dev/trunk per https://trac.osgeo.org/gdal/ticket/7159
