### ISSUE TITLE
Wrong DDL for CREATE TABLE gpkg_2d_gridded_coverage_ancillary

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#419]
- Minor issue: the use of unicode quotes make it impossible to just copy & paste the DDL and some of them are useless
- More serious issue: `grid_cell_encoding TEXT (DEFAULT grid-value-is-center)` is invalid SQL. Should be `grid_cell_encoding TEXT DEFAULT 'grid-value-is-center' `

So should be
```
CREATE TABLE gpkg_2d_gridded_coverage_ancillary (
       id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
       tile_matrix_set_name TEXT NOT NULL UNIQUE,
       datatype TEXT NOT NULL DEFAULT 'integer',
       scale REAL NOT NULL DEFAULT 1.0,
       offset REAL NOT NULL DEFAULT 0.0,
       precision REAL DEFAULT 1.0,
       data_null REAL,
       grid_cell_encoding TEXT DEFAULT 'grid-value-is-center',
       uom TEXT,
       field_name TEXT DEFAULT 'Height',
       quantity_definition TEXT DEFAULT 'Height',
       CONSTRAINT fk_g2dgtct_name FOREIGN KEY(tile_matrix_set_name) REFERENCES
               gpkg_tile_matrix_set ( table_name ) CHECK (datatype in ('integer','float')));
```

**Comment by bosborn** [comment]
This was fixed once already in #400.  Does the document need regenerated?

**Comment by rouault** [comment]
> Does the document need regenerated?

Would be nice as this is what most people will actually read :-)

**Comment by jyutzler** [comment]
I'll take a look when I get a chance but I'm at the TC meetings now so I'm not sure when I'll get to it.
