### ISSUE TITLE
R140 does not specify specific rows

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#426]
http://www.geopackage.org/spec120/#r140
In the metadata extension, we do not require specific rows. To be consistent with other extensions, we should probably add specific rows.

| *table_name* | *column_name* | *extension_name* | *definition* | *scope* |
| ------------ | ------------- | ---------------- | ------------ | ------- |
| `gpkg_metadata`   | NULL  | `gpkg_metadata`   | http://www.geopackage.org/spec120/#extension_metadata | _read-write_  |
| `gpkg_metadata_reference`   | NULL  | `gpkg_metadata`   | http://www.geopackage.org/spec120/#extension_metadata | _read-write_  |

This requirement would not be retroactive to previous versions - the ETS would only require them in starting with the version containing this fix.

**Comment by jyutzler** [comment]
This issue also applies to http://www.geopackage.org/spec120/#r145.

| *table_name* | *column_name* | *extension_name* | *definition* | *scope* |
| ------------ | ------------- | ---------------- | ------------ | ------- |
| `gpkg_spatial_ref_sys `   | `definition_12_063 `  | `gpkg_metadata`   | http://www.geopackage.org/spec120/#extension_metadata | _read-write_  |

**Comment by rouault** [comment]
This also applies to http://www.geopackage.org/spec120/#r141 (gpkg_schema)

**Comment by jyutzler** [comment]
In today's SWG we agreed to pull this into 1.2.1. I'll get on that this week.

Also we agreed to put a warning in for older versions that do not include these rows.
