### ISSUE TITLE
Req 67 and extensions

### ISSUE THREAD

**Issue by ajanett** [opengeospatial/geopackage#437]
Annex F.1 Req 67 specifies "A. /opt/extension_mechanism/extensions/data/table_def" but this reference does not exist in the document. In fact this issue is also in Annex F.6 Req 87. Given that some geopackages may not include these particular extensions shouldn't there be a test to see whether these extensions exist at all first before failing due to the anticipated extension "values" not being present? Or perhaps that is what this reference is trying to tell us to do?

**Comment by jyutzler** [comment]
I corrected the broken ATS references as part of #439. 
Note that the ETS will skip the tests for a particular extension if that extension is not detected. This is the intent of [R68](http://www.geopackage.org/spec/#r68) and [R88](http://www.geopackage.org/spec/#r88).
