### ISSUE TITLE
Requirement 78 removed but needs to be restated and included

### ISSUE THREAD

**Issue by ajanett** [opengeospatial/geopackage#442]
Requirement 78 was removed from the specification but the test for it was not removed. The test, however is still a valid test, but it needs some changes.  First of all, this is the only test that verifies the feature geometry min max values are correctly represented within the spatial trigger. That is very much a valid and useful test to be performing.  I've seen some GeoPackages that have this problem!
I suggest, therefore that Requirement 78 be re-instated but instead state something to the effect of "The spatial geometry extents of features shall be correctly represented as spatial triggers when the spatial trigger extensions are implemented."

Take a look at the test method for Req 78 and adjust it as follows:
Remove #1 and replace this with the same starting context as #19, 20, 32, etc.
Get rid of item #2: "For each Geometry Test Data Set <gtype_test> data table row for each
geometry type in Annex G, for an assortment of srs_ids, for an assortment of
coordinate values including empty geometries, without and with z and / or m
values, in both big and little endian encodings".  Because there should never be a single GeoPackage containing all of these various things and there is no way to identify this 'assortment' prior to any test.
Item #2. a. Instead of failure upon empty geometry, this test should be skipped because there may be tables that have no geometry.
Items #2b-e. Change terms such as "ST_MinX" to "Feature Extents MinX" in order to do away with the implication that spatialite extensions are required.

**Comment by jyutzler** [comment]
Ref: #438

**Comment by jyutzler** [comment]
@ajanett I'm having a hard time interpreting this. Since you have a pretty good grasp of what you want, could you please provide your own PR? I'm afraid that if I try to interpret this myself, I will get it wrong.

**Comment by ajanett** [comment]
@jyutzler This one needs to be quite similar to what you've done on pull request #450 for ETS issue #443. Instead of checking the feature envelope extents against the gpkg_contents, this one needs to check the feature envelope extents against the rtree spatial indexes extension extents for that feature. It would be only done if the extension is present, extents are present and valid for both the rtree extents table and the feature geometry BLOB.

**Comment by jyutzler** [comment]
I hear you in theory but not in execution. IIUC, the contents of the indexes are completely controlled by the triggers. I don't even know how to access them in a meaningful way.

This is why I request for you to write the PR.

**Comment by jyutzler** [comment]
As with #443, the SWG also requests a justification for the change.

**Comment by jyutzler** [comment]
In today's SWG meeting, we agreed that no action was required here. Mandating a specific index behavior is outside of the scope of this standard. In fact, such a mandate may be harmful because of the vagueness of what may happen at the boundaries.
