### ISSUE TITLE
Relax requirements on R104

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#453]
As currently written, [R104](http://www.geopackage.org/spec/#r104) ties schema elements to GeoPackage contents (ostensibly features, but presumably attributes as well). However, other tables could presumably benefit from schema definition (for example, see https://github.com/opengeospatial/geopackage-related-tables/issues/58). We could relax this requirement to allow any table defined in `gpkg_contents` or `gpkg_extensions`.

**Comment by bradh** [comment]
LGTM. Suggest it be merged.

**Comment by jyutzler** [comment]
Confirmed by SWG today.
