### ISSUE TITLE
Include as requirement the table type of the related table in Related Tables Extension 

### ISSUE THREAD

**Issue by fjlopez** [opengeospatial/geopackage#459]
The current draft of the Related Tables Extension states that related tables of `media` and `simple_attributes` relationships are GPKG tables of table type `attributes`. However, this is only stated in the informative part of the extension. The normative part shall include this requirement. I found that the NGA implementation of this extension uses the relation type as the table type of the related table (https://github.com/ngageoint/geopackage-core-java/issues/41). This behaviour conforms with the normative part of the draft, but it is not aligned with the design of the extension.

**Comment by jyutzler** [comment]
Today the SWG agreed to make this change to requirements 12 and 14. Note that mandating "attributes" for all requirements classes would not work because it would prohibit a relationship between two sets of features.
