### ISSUE TITLE
User-Defined mapping tables may be implemented as attribute tables

### ISSUE THREAD

**Issue by fjlopez** [opengeospatial/geopackage#460]
The current version of the Related Table Extension nor implicit or explicitly prohibit the implementation of user defined mapping tables as attribute tables. The draft should contains a note stating that user defined mapping tables may be implemented as attribute tables. 

The reason of this proposal is simple. GDAL 2 does not list tables not included in the `gpkg_contents` table, or when they are listed, they are not one of the standard table types (e.g. `features`, `tiles` or `attributes`). QGIS 3 uses GDAL 2 to access and manipulate GPKG and then mapping tables are not exposed to the user, making them unusable. 

I have tested converting the the mapping table into an `attributes` table (i.e. adding a `id` primary key and registering in `gpkg_contents`), exposes the mapping. Below is an screenshot of the result in GQIS3. For example, `named_place_type` is the mapping table of the relation between `named_place` (feature table) and `named_place_type_value` (attribute table). This proposal allows the use of the Related Table Extension without the need of further modifications in GDAL or QGIS. 

![captura de pantalla 2018-08-10 a las 11 17 41](https://user-images.githubusercontent.com/3294927/43949876-12dfcaf0-9c8f-11e8-9982-ca9957b7dc3c.png)

**Comment by jyutzler** [comment]
I want to hear more on this topic. What is the benefit of being able to access a mapping table directly through QGIS?  

I'm not sure how well mandating this is going to go over with existing implementations. One possibility is making a recommendation.

**Comment by tabinfl** [comment]
I think the proposed change (i.e. "user defined mapping tables MAY be implemented as attribute tables") is reasonable and should not break any well-behaved implementations.
