### ISSUE TITLE
Naming conventions for tables, columns

### ISSUE THREAD

**Issue by ajanett** [opengeospatial/geopackage#462]
The GeoPackage specification does not seem to specify naming convention rules for table names, column names, and other table content including: constraint names, trigger names, etc.  If it does, please help me to find the reference. If the reference is the pointer to SQLite, I don't think that is good enough, and will explain why below. 

In the GeoPackages that I see, all table names and column names are formed consistently with alphanumeric characters and underbars; we do not see special characters and of course, there is no initial numeric character (which actually would be illegal). Is there anyplace in the specification or in a referenced specification(s) that specifies this GeoPackage naming convention?

Yes, the GeoPackage specification references SQLite. Within SQLite, table names and field names can legally be composed with all sorts of special characters and spaces. They just must start with an alpha-character. The presence of special characters certainly would make the tables and columns far less interoperable with other databases that have much more restrictive naming conventions.

Ultimately, this is a concern because these items are all used as parameters with SQL statements and all parameters used within the SQL statements need to be verified (ex. checked for illegal characters) prior to their use within a SQL statement. I would like to be certain that the verification of SQL parameters is compliant with the specification and that the specification makes sense in terms of an implementation for GeoPackage.

Thank you for your time and consideration.

**Comment by ajanett** [comment]
Yes, @jyutzler I agree. I would like to see the specification call for underscores as separators and no other special characters allowed in the field names.

**Comment by jyutzler** [comment]
I think it is a little late to mandate this, but I can add a recommendation.

**Comment by jyutzler** [comment]
In today's SWG we agreed that a recommendation would be useful and that a mandate was not appropriate.
