### ISSUE TITLE
Geometry Question (wkb format)

### ISSUE THREAD

**Issue by achapkowski** [opengeospatial/geopackage#478]
Where can I find samples of WKB in the correct format so I can see if my converters work correctly?

**Comment by jyutzler** [comment]
Take a look at the [implementation guide](http://www.geopackage.org/guidance/implementation_guide.html#features-option).

**Comment by achapkowski** [comment]
@jyutzler this really isn't helpful.  I'm looking for like this is WKT here is geopackage WKB, etc...
Standard WKB doesn't seem to render in QGIS or ArcGIS Desktop.

**Comment by jyutzler** [comment]
This might not be as direct as you were looking for, but inside the Implementation Guide is references to sample GeoPackages. The samples containing vector data have features tables with BLOB columns containing WKB that you can pull out with a SQLite client like DB Browser 4 SQLite. 

I don't know of any sources for raw WKB values but I will ask around.

**Comment by gramnation** [comment]
@achapkowski GeoPackage requires prepending a small [binary header](http://www.geopackage.org/spec121/#gpb_spec) to a standard WKB geometry buffer. I use the geos library to read/write WKB geometry buffers and my own code to read/write/prepend the header buffer.

Running [validate_gpkg.py](https://github.com/OSGeo/gdal/blob/eb1631c9a8055c76e6483ee6bc06232bb499f096/gdal/swig/python/samples/validate_gpkg.py#L322) on your converted output GeoPackage file might provide insights.

**Comment by achapkowski** [comment]
@gramnation Thanks you for this.  I'll take a look.  Do you have any snippets on how you append the header in python?

**Comment by gramnation** [comment]
@achapkowski I don’t. [validate_gpkg.py uses struct module in order to unpack the header.](https://github.com/OSGeo/gdal/blob/eb1631c9a8055c76e6483ee6bc06232bb499f096/gdal/swig/python/samples/validate_gpkg.py#L401) Using that as a guide you might be able to pack the header.

**Comment by achapkowski** [comment]
So in a gpkg table for a MULTILINESTRING, there is an extra header of:

```python
b'GP\x00\x01\x11\x0f\x00\x00'
```

I just need to figure out how to make all these values in Python.

**Comment by danielbarela** [comment]
This is how we create the WKB that is stored in JavaScript: https://github.com/ngageoint/geopackage-js/blob/master/lib/geom/geometryData.js#L77 and Java https://github.com/ngageoint/geopackage-core-java/blob/master/src/main/java/mil/nga/geopackage/geom/GeoPackageGeometryData.java#L156 and Objective-C https://github.com/ngageoint/geopackage-ios/blob/master/geopackage-ios/geom/GPKGGeometryData.m#L80

**Comment by achapkowski** [comment]
@danielbarela thank you, I will take a look at this!

**Comment by jyutzler** [comment]
Are we satisfied here?

**Comment by achapkowski** [comment]
Figured it out.
