### ISSUE TITLE
publishing tiled gridded coverage data as wmts/wcs

### ISSUE THREAD

**Issue by MonkeySlut** [opengeospatial/geopackage#482]
Hey, it may not be the relevant place...
Is there an Implementation for publishing geopackage (contains elevation data with "Tiled Gridded Coverage Data" extension) as a service, either with WCS or WMTS?
I've tried geoserver which works fine with raster/vector geopackage as store but not for the "Tiled Gridded Coverage Data"....

**Comment by jyutzler** [comment]
I don't personally have any information on this topic other than what is at http://www.geopackage.org/implementations.html. Anyone else?

**Comment by MonkeySlut** [comment]
After some research - mapserver is able to do that via WCS
