### ISSUE TITLE
More hyperlinks throughout

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/geopackage#5]
Since we're publishing for the web it'd be good to have it use the web well, with real hyperlinks throughout. One of the places that would be best done is the normative spec references, and bibliography stuff. These footnote in to mostly hyperlinks. They should instead link straight out.

The other thing to link more is the 'clauses'. The spec refers to different clauses pretty often, would be good for people to click right there, instead of having to scroll to find it themselves. Tables similarly would be good to go to directly, but not sure how easy that is with github.

**Comment by jyutzler** [comment]
At the 3/31/15 SWG meeting we agreed to close this issue. If there are specific instances where better linking would be helpful, please propose them or submit a pull request.
