### ISSUE TITLE
Schema extension cannot be applied to attribute tables?

### ISSUE THREAD

**Issue by phidrho** [opengeospatial/geopackage#505]
Under applicability for Schema extension text says that extension may apply to any vector feature user data tables. What about attribute only tables?

> https://www.geopackage.org/spec121/index.html#extension_schema
> 
> Applicability
> This extension may apply to any Vector Feature User Data Tables.

**Comment by jyutzler** [comment]
This was already fixed in https://github.com/opengeospatial/geopackage/issues/453. It is in the set of changes staged for the next GeoPackage release.
