### ISSUE TITLE
Update Req 2 for version 1.3.0 ?

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#519]
Req 2 mentions "For GeoPackage Version 1.2.1 this value is 0x000027D9 (the hexadecimal value for 10201)".
- Should this be updated to "For GeoPackage Version 1.3.0 this value is 0x0000283C (the hexadecimal value for 10300)" ?
- Test Case ID /base/core/container/data/file_format/application_id mentions "Fail if the integer representation of the user_version string is less than 10200". Should this be changed to 10300 ? And possible add a prior step "if the integer representation of the user_version string is less than 10300, all back to the tests for GeoPackage 1.2" ?

**Comment by jyutzler** [comment]
Yeah, good point. There are a bunch of perfunctory things that have not been done yet.
