### ISSUE TITLE
Annex F.8 Metadata: triggers on gpkg_metadata_reference.reference_scope dropped on purpose ?

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#520]
https://portal.ogc.org/files/92744#_allow_metadata_scopes_to_be_extended_annex_f_8 mentions the removal of triggers on gpkg_metadata.md_scope, but I also see that those on  gpkg_metadata_reference.reference_scope (gpkg_metadata_reference_reference_scope_insert, etc..) enforcing Requirement 96 "Every gpkg_metadata_reference table reference scope column value SHALL be one of 'geopackage', 'table', 'column', 'row', 'row/col' in lowercase." are no longer there. Is this on purpose ? If so, could be worth mentioning it in the changelog

**Comment by jyutzler** [comment]
Fixed via https://gitlab.com/imagemattersllc/ogc18-066/-/commit/bc9e9bd15b03d6bd38153aff7b310fc117178c3c
