### ISSUE TITLE
Eliminate validation triggers in Annex D

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#524]
There are a whole bunch of validation triggers in [Annex D](http://www.geopackage.org/spec121/index.html#_trigger_definition_sql_informative). These are dangerous because, if implemented, then can inhibit extensibility. It may be prudent to get rid of all of these triggers moving forward.

**Comment by jyutzler** [comment]
Today the SWG decided to leave these triggers in place but to add some explanatory text. See https://github.com/opengeospatial/geopackage/pull/528/commits/a83dc966a799af187eec3d9732ad1037d8b365f3.

**Comment by danielbarela** [comment]
The validation triggers are there to literally validate that the GeoPackage remains spec compliant, enhancing interoperability.  If clients are allowed to write extensions which violate the spec (negative zoom levels, etc), and in turn, remove triggers which would have prevented this violation, we can no longer trust that a GeoPackage actually follows the spec.  Extensions should not be allowed to violate the spec and the triggers are there to validate they do not.  Suggesting that triggers can be changed to allow invalid GeoPackages seems dangerous from an interoperability standpoint.

**Comment by jyutzler** [comment]
That may have been the original intent, but it was badly executed and conflicts with other OGC tenets. One of them is Requirement 25 of the [OGC Modular Specification](https://portal.opengeospatial.org/files/?artifact_id=34762) which states:

> A specification conformant to this standard shall never restrict in any manner future, logically-valid extensions of its standardization targets.

We've found multiple instances where these triggers add no value and just cause problems, for example metadata scopes (#512). Requirement #94 was backed by a trigger which is just wrong.

It turns out that the real GeoPackage interoperability risks are generally in things that the triggers can't handle.

**Comment by danielbarela** [comment]
ok.
