### ISSUE TITLE
metadata extension identifier

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/geopackage#527]
cc @pvgenuchten

In https://github.com/opengeospatial/geopackage/blob/master/spec/annexes/extension_metadata.adoc#metadata-table, column `id` is defined as an INTEGER.

Has there been consideration of an `md_identifier (TEXT)` as a means to provide a given metadata row's true identifier (which may be a URN, UUID, etc.)?  This value would map into a given metadata record's `<gmd:fileIdentifier>` or `<dc:identifier>` value (without having to dive into the `metadata` column).

**Comment by jyutzler** [comment]
Alas, no, there are no plans for this. We are reluctant to extend this table. If this information is important to you, the best thing might be to declare a join table and put the URN/UUID in there.

**Comment by jyutzler** [comment]
If there are no objections, we would like to close this issue.
