### ISSUE TITLE
`ST_Empty` should be `ST_IsEmpty` to match the RTree Extension SQL Function specification.

### ISSUE THREAD

**Issue by bosborn** [opengeospatial/geopackage#529]
`ST_Empty` should be `ST_IsEmpty` to match the RTree Extension SQL Function specification.
The case of the existing functions should probably be corrected as well: `ST_MinX`, `ST_MaxX`, `ST_MinY`, `ST_MaxY`

_Originally posted by @bosborn in https://github.com/opengeospatial/geopackage/pull/518/files_

**Comment by jyutzler** [comment]
fixed by #518

**Comment by bosborn** [comment]
@jyutzler This was a comment about the incorrect fix made in #518 and does not appear resolved.
Open and fixed in #535.

**Comment by jyutzler** [comment]
Got it. Will discuss during today's SWG.
