### ISSUE TITLE
Datetime and timezones

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/geopackage#530]
I have a few questions regarding requirement 5 and table 1, GeoPackage Data Types

> Data Type | Size and Description
> -- | --
> DATETIME | ISO-8601  date/time string in the form YYYY-MM-DDTHH:MM:SS.SSSZ with T separator  character and Z suffix for coordinated universal time (UTC) encoded in  either UTF-8 or UTF-16. See TEXT. Stored as SQLite TEXT.

So the table says "ISO-8601  date/time string in the form YYYY-MM-DDTHH:MM:SS.SSSZ with T separator  character and Z suffix for coordinated universal time (UTC)".

As I read this, that means that 

✔️ 2018-03-01T10:13:19Z is allowed
❌ 2018-03-01T11:13:19+01:00 is not allowed
❌ 2018-03-01T10:13:19 is not allowed

According to https://sqlite.org/datatype3.html

> SQLite does not have a storage class set aside for storing dates and/or times. Instead, the built-in Date And Time Functions of SQLite are capable of storing dates and times as TEXT, REAL, or INTEGER values: TEXT as ISO8601 strings ("YYYY-MM-DD HH:MM:SS.SSS"). [...]

According to https://sqlite.org/lang_datefunc.html

> [...] Formats 2 through 10 may be optionally followed by a timezone indicator of the form "[+-]HH:MM" or just "Z". The date and time functions use UTC or "zulu" time internally, and so the "Z" suffix is a no-op. Any non-zero "HH:MM" suffix is subtracted from the indicated date and time in order to compute zulu time. For example, all of the following time strings are equivalent:
> 
>     2013-10-07 08:23:19.120
>     2013-10-07T08:23:19.120Z
>     2013-10-07 04:23:19.120-04:00
>     2456572.84952685 

This is also illustrated by this query:

```
sqlite> select datetime('2018-03-01T10:13:19Z'), datetime('2018-03-01T11:13:19+01:00'), datetime('2018-03-01T10:13:19');
2018-03-01 10:13:19|2018-03-01 10:13:19|2018-03-01 10:13:19
```

2018-03-01T10:13:19 would be a local time (with the location unspecified) according to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators) and would be UTC time according to SQLite, so it makes sense not to allow datetimes without time zone information, in order to avoid confusion.

❓ But 2018-03-01T11:13:19+01:00 is a valid ISO 8601 string, so is there a reason why 2018-03-01T11:13:19+01:00 does not seem to be allowed according to the GeoPackage spec? Or should the standard be updated so that 2018-03-01T11:13:19+01:00 would be allowed too?

❓And an additional question: test case /base/core/container/data/table_data_types , that tests requirement 5, tests only that the data type names are the ones from table 1. It does not test the format of the data in columns having datatype DATETIME. So a cell with data type DATETIME and value 2018-03-01T10:13:19 would not be reported as an error. Should the test (and the ETS) be updated? Perhaps with an option to disable testing of actual data (in the case of huge files)?

**Comment by jyutzler** [comment]
This is tricky. You are right that there is potentially a hole in the standard. I am reluctant to agree to a change to the standard as part of 1.3. Are clients just pulling in the strings or are they calling `datetime()` on them? That makes a big difference in terms of interoperability.

**Comment by heidivanparys** [comment]
I listened again to the recording of the meeting where this was discussed, and noticed the second question wasn't discussed there. The summary of the answer to the first question was that the intent was to use UTC times in all `DATETIME` fields, therefore `2018-03-01T10:13:19Z` is expected to be used and `2018-03-01T11:13:19+01:00` is not expected to be used.

To illustrate the second question, I created a simple GeoPackage file containing the following table:

```sql
CREATE TABLE IF NOT EXISTS "myfeaturetype" (
	"_id"	INTEGER NOT NULL,
	"mydatetime"	DATETIME NOT NULL,
	"location"	POINT,
	"label"	TEXT NOT NULL,
	PRIMARY KEY("_id" AUTOINCREMENT)
);
```

and added data (using the latest Spatialite release, 5.0.0-RC1):

```sql
select autogpkgstart();
insert into myfeaturetype (label, mydatetime, location) values ('UTC time', '2020-08-18T09:02:00Z', gpkgmakepoint(722125, 6178892, 25832));
insert into myfeaturetype (label, mydatetime, location) values ('time with time zone', '2020-08-18T11:02:00+02:00', gpkgmakepoint(722130, 6178892, 25832));
```

That GeoPackage file, containing a DATETIME value that does not comply with what is written in http://www.geopackage.org/spec121/#table_column_data_types 

> ISO-8601 date/time string in the form YYYY-MM-DDTHH:MM:SS.SSSZ with T separator character and Z suffix for coordinated universal time (UTC) [...]

Nevertheless, the GeoPackage file passes the ETS-test (see last screenshot below). Because requirement 5 does not state explicitly that the columns should follow the semantics of the data type, only that the names specified in the table, including `DATETIME`, should be used.

> The columns of tables in a GeoPackage SHALL only be declared using one of the data types specified in table GeoPackage Data Types. [...]

Requirement 15 and requirement 100 test for date formats, but only for specific columns: `gpkg_contents.last_change` and `gpkg_metadata_reference.timestamp`.

So my question was: if the intent is indeed to only allow UTC times, shouldn't this be reflected in requirement 5? And as result, in the ATS and the ETS, that should test all fields having a `DATETIME` datatype?

Bonus info:

The GDAL driver seems to deal with the timestamps well, recognizing the time zones:

```
ogrinfo -q mydata.gpkg myfeaturetype

Layer name: myfeaturetype
OGRFeature(myfeaturetype):1
  mydatetime (DateTime) = 2020/08/18 09:02:00+00
  label (String) = UTC time
  POINT (722125 6178892)

OGRFeature(myfeaturetype):2
  mydatetime (DateTime) = 2020/08/18 11:02:00+02
  label (String) = time with time zone
  POINT (722130 6178892)
```

I can't figure out how to display time zones properly in QGIS, if possible at all. Without changing settings, it turns up like the first screenshot below, when changing settings, it doesn't really get better:

![image](https://user-images.githubusercontent.com/11427611/90514193-23fbc000-e161-11ea-9205-277aae18ecdf.png)

![image](https://user-images.githubusercontent.com/11427611/90514369-61604d80-e161-11ea-8bcf-b210369c5557.png)

![image](https://user-images.githubusercontent.com/11427611/90514404-6d4c0f80-e161-11ea-93c2-37f3068118c8.png)


![image](https://user-images.githubusercontent.com/11427611/90513271-a6838000-e15f-11ea-983e-dd61291186b9.png)

**Comment by jyutzler** [comment]
From Keith Ryden at today's SWG meeting: it would be useful to know a use case where this is needed. Supporting time zones would introduce complexity and potentially cause problems.

**Comment by heidivanparys** [comment]
@jyutzler Work is being done in the INSPIRE community to see how INSPIRE data could be distributed in GeoPackage files. A GitHub repo was created last week to help support that work. The question on the time zones is also posted there, see https://github.com/INSPIRE-MIF/gp-geopackage-encodings/issues/1.

**Comment by fjlopez** [comment]
Supporting time zones in SQLite has been always an issue for developers. Either they convert all timestamps to UTC, and can use SQL for searching, sorting and other computations with dates (all SQLite date-time functions assume that date and time are stored internally in UTC), or they leave the time zone information but all searching, sorting and other computations with dates are done in the application or in a SQLite wrapper library (e.g. GDAL with DATETIME_FORMAT=WITH_TZ https://github.com/OSGeo/gdal/issues/2898 ) because SQLite functions don't recognise such strings as valid datetimes and the results are undefined. 

@heidivanparys, SQLite has a [modifier](https://sqlite.org/lang_datefunc.html) in its datetime functions that can be helpful here:
  
> The "localtime" modifier (12) assumes the time string to its left is in Universal Coordinated Time (UTC) and adjusts the time string so that it displays localtime. If "localtime" follows a time that is not UTC, then the behavior is undefined. The "utc" modifier is the opposite of "localtime". "utc" assumes that the string to its left is in the local timezone and adjusts that string to be in UTC. If the prior string is not in localtime, then the result of "utc" is undefined.

A possible approach is to recommend for INSPIRE data, e.g., to use:

-  `datetime(timestring, 'utc')` in `INSERT` and `UPDATE` statements when users want to store a `timestring` which is in local TZ.
-  `datetime(timestring, 'localtime')` in `SELECT` statements when users want to retrieve `timestring` converted to local TZ.

Similar to the note of the datatype `TEXT` regarding to the impact of `PRAGMA encoding`, I wonder if we could add a note in the spec explaining the use of SQLite date/time functions for dealing with localtime in `DATE` and `DATETIME` .

**Comment by jyutzler** [comment]
In today's OAB meeting, the OAB recommends that standards conform to the UTC time as specified in both OWS Common and the existing GeoPackage text. Here is what OWS Common says, which is consistent with the GeoPackage text.

> A default time zone of UTC as defined by ISO 8601:2004 and ISO 8601:2000 (or Greenwich Mean Time, also referred to as ―Z‖ for Zulu Time), shall be used for all temporal data passed or returned to/from OGC Web Services.

Ref: https://portal.ogc.org/?m=projects&a=view&project_id=228&tab=5&act=details&issue_id=1491

**Comment by heidivanparys** [comment]
@jyutzler  Good to see a clarification of this issue. I would like to repeat one of my first questions though before leaving this issue completely:

> ❓And an additional question: test case /base/core/container/data/table_data_types , that tests requirement 5, tests only that the data type names are the ones from table 1. It does not test the format of the data in columns having datatype DATETIME. So a cell with data type DATETIME and value 2018-03-01T10:13:19 would not be reported as an error. Should the test (and the ETS) be updated? Perhaps with an option to disable testing of actual data (in the case of huge files)?

**Comment by heidivanparys** [comment]
@jyutzler There is also the suggestion from @fjlopez that should be discussed, or has that been done already?

> Similar to the note of the datatype TEXT regarding to the impact of PRAGMA encoding, I wonder if we could add a note in the spec explaining the use of SQLite date/time functions for dealing with localtime in DATE and DATETIME .

**Comment by rcoup** [comment]
@heidivanparys in sqlite you can put any type into any field regardless of the field definition... not sure why datetimes would want special type checking?

**Comment by heidivanparys** [comment]
> 
> 
> in sqlite you can put any type into any field regardless of the field definition... not sure why datetimes would want special type checking?

@rcoup I see your point, my last question is actually more general and not only for datetimes.

### Background

In my agency, we would like to make more use of the OGC validator and encourage our partners to use the OGC validator actively (procurement, contracts with IT companies for development of tools, ...) to enforce OGC compliance, but that only works if the ATS and ETS are reliable and complete, and we do not have to implement a bunch of extra checks ourselves.

### My expectation until recently

The ATS and therefore the ETS are supposed to check whether a GeoPackage file is compliant to the GeoPackage specification. When a GeoPackage file is using non-UTC datetimes, then for me, the expectation is that the file is not compliant to the GeoPackage spec, and I would like to see that in the test report of the ETS.

### What does the spec actually say?

Do I misunderstand the specification? Because requirement 5 indeed says (highlighting is mine)

> The columns of tables in a GeoPackage SHALL only be **declared** using one of the data types specified in table GeoPackage Data Types.

The spec does **not** say that values actually have to conform to the declared type.

### Rephrased question

So my question is:

- Is a GeoPackage file that has non-UTC datetimes in a DATETIME column compliant to the GeoPackage spec?
- Is a GeoPackage file that has e.g. value 2 in a BOOLEAN column compliant to GeoPackage spec?
- Similar questions for the other types

Or rephrased again:

- Should the ETS turn green or red for a GeoPackage file that has non-UTC datetimes in a DATETIME column?
- Should the ETS turn green or red for a GeoPackage file that has e.g. value 2 in a BOOLEAN column?
- Similar questions for the other types

@jyutzler Let me know if I should open a new issue for this or not.

**Comment by fjlopez** [comment]
@heidivanparys, I think that [requirement 4](https://www.geopackage.org/spec121/#r4) clarifies this. It says (highlighting is mine):
> A GeoPackage SHALL only contain the data elements (tables, columns, or **values**) and SQL constructs (views, constraints, or triggers) specified in the core of this encoding standard (Features, Tiles, and Attributes). Extended GeoPackages MAY contain additional data elements and SQL constructs as specified through the Extension Mechanism.

According Requirement 4, the only data types that can be used are those defined in table  GeoPackage Data Types, which defines each data type as a constrained SQLite data type, e.g. for the BOOLEAN data type:
> A boolean value representing true or false. Stored as SQLite INTEGER with value 0 for false or 1 for true.

Thus, a value 2 in a BOOLEAN column does not conform to Requirement 4. IMHO, the ETS should check this. I do not know the current level of support in the ETS of this requirement.

**Comment by rduivenvoorde** [comment]
My I add a comment: by not being very strict in the format of the DATETIME strings, current (gdal?) time related queries are pretty ambiguous in my opinion.

See: https://github.com/OSGeo/gdal/issues/3423 where I propose to stay away from handling timezones (VERY difficult), and stick to storing Zulu time only (or millisecondssinceepoch) and/or learn from Postgresql...

**Comment by chris-little** [comment]
Maybe rather late to contribute to this discussion, but if the Z is omitted from an ISO8601 string, it implies "local time", whatever that is - it may be solar time by a sundial. That is why the OAB recommendation mandated the `Z`. 

Also, as the original 1988 ISO8601 was updated in 2000, 2004 and 2019, the concept of "now" was removed, but the times of both 24:00:00 and 00:00:00 were re-allowed!
