### ISSUE TITLE
Editorial comments regarding simple features references

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/geopackage#531]
Some minor editorial comments regarding the references:

- It seems that OGC 05-134 and OGC 99-049 have the same contents but different formatting. See also https://www.ogc.org/standards/sfs
- It is OGC 05-134 that is the same as ISO 19125-2:2004 when looking at formatting etc., not OGC 99-049
- It is version 1.1 of SFA-CA that is the same as ISO 19125-1:2004, not version 1.2.1
- ISO 19125-2 was withdrawn by ISO/TC 211 (search for ISO 19125-2 on https://committee.iso.org/sites/tc211/home/resolutions.html)

So I think that

```
- [[[9]]] OGC 06-103r4 OpenGIS® Implementation Standard for Geographic information - Simple feature access - Part 1: Common architecture Version: 1.2.1 2011-05-28 http://portal.opengeospatial.org/files/?artifact_id=25355 (also ISO/TC211 19125 Part 1)
- [[[10]]] OGC 06-104r4 OpenGIS® Implementation Standard for Geographic information - Simple feature access - Part 2: SQL option Version: 1.2.1 2010-08-04 http://portal.opengeospatial.org/files/?artifact_id=25354 (also ISO/TC211 19125 Part 2)
- [[[11]]] OGC 99-049 OpenGIS® Simple Features Specification for SQL Revision 1.1 5, 1999, Clause 2.3.8 http://portal.opengeospatial.org/files/?artifact_id=829 May
```
should be replaced with something like

```
- [[[9]]] OGC 06-103r4 OpenGIS® Implementation Standard for Geographic information - Simple feature access - Part 1: Common architecture Version: 1.2.1 2011-05-28 http://portal.opengeospatial.org/files/?artifact_id=25355
- [[[10]]] OGC 06-104r4 OpenGIS® Implementation Standard for Geographic information - Simple feature access - Part 2: SQL option Version: 1.2.1 2010-08-04 http://portal.opengeospatial.org/files/?artifact_id=25354 (the older version 1.1 of this standard is known as ISO 19125-1:2004)
- [[[11]]] OGC 05-134 OpenGIS® Implementation Specification for Geographic
information - Simple feature access - Part 2: SQL option Version 1.1.0 2005-11-22 http://portal.opengeospatial.org/files/?artifact_id=13228 (also known as the now withdrawn ISO 19125-2:2004)
```

It probably should be double-checked by someone of the OGC staff.

**Comment by jyutzler** [comment]
I asked @ogcscotts to look at this.
Some of these references might still be useful, even though they are out of date. For example 19125 is still useful, even though it is superceded by ISO 19107.

**Comment by ogcscotts** [comment]
@heidivanparys @jyutzler Sorry for the delay - wanted to confirm through approval records the content of reference 11. Heidi's suggestion is correct: OGC 05-134 is identical in normative content to OGC 99-049. The only differences are minor editorial changes from ISO in the publication of ISO 19125-1:2004.
