### ISSUE TITLE
Indexed min and max values differ from data - is this normal behaviour?

### ISSUE THREAD

**Issue by phidrho** [opengeospatial/geopackage#532]
I have a GeoPackage file created with QGIS 3.12.3. (It uses old version of update3 trigger, but I did only insertion of data, so broken update3 trigger it is not triggered in this case).

For GPKG functions I'm using [libgpkg in latest ver. 0.9.18](https://bitbucket.org/luciad/libgpkg/src/default/) 

I have created some data inside QGIS, and then ran this query to check indexes:

```sql
SELECT
    a.fid AS feature_id,
    ST_MinX(a.geometry) AS calculated_MinX,
    ST_MinY(a.geometry) AS calculated_MinY,
    ST_MaxX(a.geometry) AS calculated_MaxX,
    ST_MaxY(a.geometry) AS calculated_MaxY,
    b.id AS index_id,
    b.minx AS indexed_MinX,
    b.miny AS indexed_MinY,
    b.maxx AS indexed_MaxX,
    b.maxy AS indexed_MaxY,
    ST_MinX(a.geometry) - b.minx AS delta_MinX,
    ST_MinY(a.geometry) - b.miny AS delta_MinY,
    ST_MaxX(a.geometry) - b.maxx AS delta_MaxX,
    ST_MaxY(a.geometry) - b.maxy AS delta_MaxY

FROM
    poly_layer a
    LEFT JOIN rtree_poly_layer_geometry b ON
        a.fid = b.id
```

For MaxY it has almost 1 meter difference on feature with id=6:

| feature_id |    calculated_MinX |   calculated_MinY |    calculated_MaxX |   calculated_MaxY | index_id | indexed_MinX | indexed_MinY | indexed_MaxX | indexed_MaxY |           delta_MinX |          delta_MinY |             delta_MaxX |           delta_MaxY |
| ---------: | -----------------: | ----------------: | -----------------: | ----------------: | -------: | -----------: | -----------: | -----------: | -----------: | -------------------: | ------------------: | ---------------------: | -------------------: |
|          1 |  475605.4296875002 | 5045394.704496659 |  476409.3547232826 | 5045973.939050571 |        1 |   475605.375 |    5045394.5 | 476409.40625 |      5045974 |  0.05468750017462298 | 0.20449665933847427 |  -0.051526717375963926 | -0.06094942893832922 |
|          2 |  476353.9116173666 | 5045717.149928434 | 476912.71976383607 | 5046004.578661735 |        2 | 476353.90625 |      5045717 | 476912.78125 |      5046005 | 0.005367366597056389 | 0.14992843382060528 |   -0.06148616393329576 |  -0.4213382648304105 |
|          3 |  476409.3547232826 | 5045973.939050571 |  476920.0149093513 | 5046273.040016698 |        3 | 476409.34375 |    5045973.5 |  476920.0625 |    5046273.5 | 0.010973282624036074 |  0.4390505710616708 |  -0.047590648697223514 |  -0.4599833022803068 |
|          4 |  475857.8417223284 | 5045957.889730438 |  476448.7485090651 | 5046360.581762881 |        4 | 475857.78125 |    5045957.5 |    476448.75 |      5046361 |  0.06047232839046046 | 0.38973043765872717 | -0.0014909349265508354 |  -0.4182371189817786 |
|          5 | 475590.83939646964 | 5045696.723520991 |  476053.3516221376 | 5046084.825262404 |        5 | 475590.78125 |    5045696.5 | 476053.40625 |      5046085 |  0.05814646964427084 | 0.22352099139243364 |   -0.05462786240968853 | -0.17473759595304728 |
|          6 |  475946.8424976147 | 5045245.883528148 |  476782.8661736643 | 5045769.674976144 |        6 | 475946.78125 |    5045245.5 |   476782.875 |    5045770.5 |  0.06124761467799544 |  0.3835281478241086 |  -0.008826335717458278 |  -0.8250238560140133 |

[rtree_test.gpkg.zip](https://github.com/opengeospatial/geopackage/files/4728123/rtree_test.gpkg.zip)

**Comment by bosborn** [comment]
There is an expected roundoff error:
https://www.sqlite.org/rtree.html#roundoff_error

**Comment by jyutzler** [comment]
We'll add a note to annex F.3. Clients may wish to pad their values when querying, but we can't be too specific on that because each client is different.
