### ISSUE TITLE
Statement on WKB and axis order in specification

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/geopackage#540]
Endnote 11 of the specification states:

> The axis order in WKB is always (x,y{,z}{,m}) where x is easting or longitude, y is northing or latitude, z is optional elevation and m is optional measure.

That endnote was introduced in the resolving of #54.

However, I haven't been able to find a clear description of axis order in the WKB specifications. In a [recent discussion in the user group for Spatialite](https://groups.google.com/g/spatialite-users/c/-sbd9F5Batc) on the release of version 5.0.0 of Spatialite (that, as some previous versions of Spatialite, has GeoPackage support), it was said that 

> As far as I know WKT and EWKT are still using traditional GIS order (recent MySQL version makes an exception, there may be others)

When trying to find more information about axis order and WKT, I came across the article [Axis Order in Spatial Data](https://www.safe.com/blog/2009/03/axis-order-in-spatial-data/), that mentions both WKT and WKB, and that states:

> In a series of decisions, the Open Geospatial Consortium (OGC) has decided that going forward their formats will respect the authority’s axis order, which led to a painful transition for WMS and WFS. Also interesting is the case for the Simple Features WKT and WKB geometry formats, which have not been updated since the latest policy statement. All known implementations of these formats use longitude followed by latitude for geodetic data. Even Informix’s Geodetic DataBlade, which internally uses latitude/longitude, reads and writes WKB as longitude/latitude. When Microsoft introduced spatial support in SQL Server, their geodetic type briefly read WKT and WKB in latitude/longitude order, which led to lively discussion, a retraction, and eventually a five pound box of chocolates. It will be interesting to see what happens when and if these standards are updated.

So my question is: wouldn't it be more correct to state in the GeoPackage specification that 

_The axis order in WKB stored in a GeoPackage follows the de facto standard for axis order in WKB and is therefore always (x,y{,z}{,m}) where x is easting or longitude, y is northing or latitude, z is optional elevation and m is optional measure._

**Comment by jyutzler** [comment]
Heidi,
I think what you are looking for is in Section 8.2.8 of 06-103r4 which is a normative reference.

```
8.2.8 Description of WKBGeometry representations
The Well-known Binary Representation for Geometry is described below. The basic building block is the
representation for a Point, which consists of a number Doubles, depending on the coordinate referece system in
use for the geometry. The representations for other geometric objects are built using the representations for
geometric objects that have already been defined.
// Basic Type definitions
// byte : 1 byte
// uint32 : 32 bit unsigned integer (4 bytes)
// double : double precision number (8 bytes)
// Building Blocks : Coordinate, LinearRing
Point {
 double x;
 double y} 
PointZ {
 double x;
 double y;
 double z}
PointM {
 double x;
 double y;
 double m}
PointZM {
 double x;
 double y;
 double z;
 double m} 
...
```

**Comment by heidivanparys** [comment]
> I think what you are looking for is in Section 8.2.8 of 06-103r4 which is a normative reference.

Thanks for the reply. I cannot find anything in 06-103r4 that says that "x is easting or longitude, y is northing or latitude".

I had a look at [this lengthy thread](https://social.msdn.microsoft.com/Forums/Windowsserver/en-US/41250c42-25e6-4de7-953e-a6c41ada383f/xy-coords-reversed-in-wkt-wkb-methods-in-nov-ctp?forum=sqlspatial), that is referred from the blog mentioned above, and there it is also written that "x is easting or longitude, y is northing or latitude" is the industry interpretation of the WKB standard.

**Comment by rcoup** [comment]
@heidivanparys https://wiki.osgeo.org/wiki/Axis_Order_Confusion and [OGC Revision to Axis Order Policy and Recommendations (08-038r7)](https://portal.opengeospatial.org/files/76024) have some more background and discussion.

**Comment by pepijnve** [comment]
@heidivanparys the way I remember it the SWG decided (or at least I argued for and implemented) what's now described as case 2 in the OGC axis order policy document referenced by @rcoup.

WKB and WKT both define the order in which the fields named `x`, `y`, and `z` occur in their respective encodings, there's no ambiguity there. But those specifications do not assign semantics to these fields. They're essentially three named variables.

The question then is what the meaning of `x`, `y` and `z` are. Do you map these to the order of the axes or the direction of the axes?

The endnote is/was intended to state that it's the latter. The `x` field is used to store the value for the `east`/`west`/`geocentricX` axis, `y` for the `north`/`south`/`geocentricY` axis, `z` for the `up`/`down`/`geocentricZ` axis.
If my memory serves me well, my rationale for arguing for this at the time was that for non-CRS savvy systems this is the more predictable approach. Sure, you still need to know if you're dealing with geodetic, projected or geocentric coordinates, but you don't need to really interpret the CRS to know where to find longitude, latitude, northing, easting, ...
Making the semantics of `x` and `y` dependent on the CRS specification on the other hand requires each system to either be able to parse and interpret the CRS WKT or have some external source of truth like the EPSG database. I felt that having that requirement would put a greater burden on software developers trying to work with geopackage encoded data.

**Comment by heidivanparys** [comment]
@rcoup @pepijnve  Thank you for your replies (and sorry for my late reply!), that is useful information.

I had a look again at the OGC Axis Order Policy document.

> the way I remember it the SWG decided (or at least I argued for and implemented) what's now described as case 2 in the OGC axis order policy document referenced by @rcoup.

When reading through the cases, isn't the GeoPackage specification an example of case 4 instead?

> Case 2: Payload encoding explicitly overrides the Axis Order as specified in the CRS metadata: In this case the payload explicitly encodes additional metadata in order to determine axis order. For example, in the draft ISO 19107 (Draft International Standard), axis "reordering" may be included as a CS transformation in payload comments. The included CS transformation must reference the axis names actually defined by the CRS metadata.

> Case 4: The Encoding specification (document) explicitly overrides the Axis Order as specified in the CRS metadata: In this case, a specification (document) specifies a default CRS but then overrides the axis order of the CRS as specified in the CRS metadata. A typical example is to specify WGS 84 (EPSG 4326) in the specification but then state in the document that the axis order is the opposite of the CRS metadata. The payloads would then be encoded using the axis order as specified in the spec document and not in the CRS metadata. The OGC does not recommend implementing this use case.

http://www.geopackage.org/spec121/#gpb_spec does not say anything about metadata to determine axis order. Whereas the endnote says that 

> The axis order in WKB is always (x,y{,z}{,m}) where x is easting or longitude, y is northing or latitude, z is optional elevation and m is optional measure.

so if I understand that correctly the specification explicitly overrides the axis order of any coordinate reference systems specified, and perhaps the statement could be modified to make this clear:

_The axis order in WKB stored in a GeoPackage follows the de facto standard for axis order in WKB and is therefore always (x,y{,z}{,m}) where x is easting or longitude, y is northing or latitude, z is optional elevation and m is optional measure. Note: this means that this specification applies case 4 from 08-038r7, Revision to Axis Order Policy and Recommendations_

(and the reason for using case 4 despite the fact that it is not recommended is of course the dependency on WKB, and de facto standard for axis order in WKB).

**Comment by pepijnve** [comment]
@heidivanparys sorry, you're right it's case 4; not 2.
