### ISSUE TITLE
ISO 19162/OGC, OGC® 12-063r5/12-063r7

### ISSUE THREAD

**Issue by KRyden** [opengeospatial/geopackage#541]
Geopackage CRS description extension for WKT2 references OGC® 12-063r5.  It should also reference the updated OGC® 12-063r7 document which was released after the extension was adopted.  These documents are compatible.

This is an informational update and we should try to pick this up in the pending GeoPackage 1.3 document.

**Comment by KRyden** [comment]
Adding recommended wording from an email sent by Jim Ressler, NGA to the Geopackage SWG 4 September 2020:

For the GeoPackage profile for DGIWG, I recommend allowing both 12-063 and 18-010 as you suggested, using extension F.10.

I stated it this way with some constraints to ensure backward compatibility. When this is improved in a future GeoPackage release, I think there should be a WKT field to indicate to the user of the gpkg which WKT version is being used.

Start proposed statement:

OGC 12-063r5 and 18-010r7 / ISO 19162 specifies a WKT encoding for a 3D geodetic CRS, and a way to correctly specify the axis directions for polar stereographic projections, which are required for this profile. The WKT values in the gpkg_spatial_ref_sys columns are dependent upon the definition column in the gtpk_spatial_ref_sys extension gpts_crs_wkt. GeoPackage extension F.10 shall be used with both 12-063 and 18-010 WKT field definition_12_063. For backwards compatibility, only use common WKT values between 12-063 and 18-010. Additional WKT values in 18-010r7 can be used when required in the CRS definition.

Note, Extension F.10 Requirement 117 in GeoPackage 1.2.1 and 1.3 states that column definition_12_063 takes precedence if both definition values are defined. The WKT values in 18-010r7 can be placed in the gpkg_crs_wkt table that are new or use terms consistent with 12-063r5.

**Comment by jyutzler** [comment]
@KRyden in response to #499, we updated the reference to WKT2 to https://docs.opengeospatial.org/is/18-010r7/18-010r7.html in #507. Is this what you want or should we add an additional reference to 12-063r7?
