### ISSUE TITLE
Does byte flag in GeoPackageBinary about the endianness refer to whole header, or only to envelope?

### ISSUE THREAD

**Issue by phidrho** [opengeospatial/geopackage#548]
I have a question about the endianness part under the "2.1.3.1.1. BLOB Format" in the specification.

The specification says: "B: byte order for header values (1-bit Boolean)".
So does this information refers only to the envelope part of GeoPackage BLOB, or to the entire header?

This is my input data:

```text
srs_id = 3765
wkt = LineString (355751.03 5051851.43, 355754.92 5051855.1)
xmin = 355751.03
xmax = 355754.92
ymin = 5051851.43
ymax = 5051855.10
```

```text
header_pt1_hex: 47 50
header_pt2_hex: 00
header_pt3a_hex: 02                // RRXYEEEB 00000010
header_pt3b_hex: 00 00 0e b5       // srid 3765 as int32
header_pt4_hex:
    [
        4115b69c1eb851ec   //355751.03
        4115b6abae147ae1   //355754.92
        41534572db851eb8   //5051851.43
        41534573c6666666   //5051855.10
    ]
```

I have an example for this line string in little endian, generated with SpatiaLite:
`47 50 00 03 b5 0e 00 00 ec51b81e9cb61541 e17a14aeabb61541 b81e85db72455341 666666c673455341` 

So I used big-endian flag, should it look like this:
`47 50 00 02 00 00 0e b5 4115b69c1eb851ec 4115b6abae147ae1 41534572db851eb8 41534573c6666666`

or should I reverse the `header_pt1_hex` (letters GP) also, as it is also part of header ("B: byte order for **header** values (1-bit Boolean)"):
`50 47 00 02 00 00 0e b5 4115b69c1eb851ec 4115b6abae147ae1 41534572db851eb8 41534573c6666666`

Does this endianness flag refers to the WKB part also, or is it just for the header part?

**Comment by jyutzler** [comment]
KR: The headers were added for GeoPackage so the flag applies to the second part, not the first part

**Comment by phidrho** [comment]
So the header part should always be in little-endian and this information is only for WKB part?

If this is the correct case, I suggest changing the text in specification from:
`B: byte order for header values (1-bit Boolean)`

to:
`B: byte order for WKB values (1-bit Boolean)`

**Comment by pepijnve** [comment]
@phidrho https://github.com/luciad/libgpkg/blob/master/gpkg/gpkg_geom.c#L43 might help. The goal of the geopackage blob format was to have a geopackage specific header followed by standard WKB. The endianness bit applies only to multi-byte values in the header itself. The endianness of the WKB part is as per the WKB specification.

**Comment by phidrho** [comment]
@pepijnve OK, thnx. I'm not a programmer so It's a bit hard for me to fully understand the C code. I'm working on some paper for geodetic conference about GeoPackage, so I didn't want to write something wrong in paper.

Only this part of text in specification about endianness is confusing for me. Since GPKG BLOB has two parts (header + WKB), and header is also split to two parts, but it is presented with 6 bullets in specification, and after all this we have text which says byte order for header values.

I know that public comment has ended for 1.3, but if I still can make a proposal, it would be to change this text to something which is more specific, e.g.:

`B: byte order for SRS_ID and envelope values in header (1-bit Boolean)`

**Comment by pepijnve** [comment]
> I'm not a programmer so it's a bit hard for me to fully understand the C code.

Oh sorry, my mistake. It seemed like a programmery question. In human language, when reading (the same steps apply to writing) the header you need to:

1. Read the two magic bytes. That should always be the ASCII characters `G` followed by `P`.
2. Read the version byte. This should always be 0 (zero).
3. Read the flags byte. This least significant bit in this byte indicates byte ordering for the values in the geopackage header that follow
4. Read the srs id using the byte order obtained in step 3
5. Depending on the envelope flags that are set read zero, four or six 64-bit floating point values using the byte order obtained in step 3

You can then proceed to read the WKB that follows. The first byte of every WKB geometry is a field named byteOrder. When reading/writing the WKB this is the byte order you need to use. In other words, the byte ordering of multi-byte values in the header and the WKB are independent. You do not need one to correctly parse the other. In practice, most implementations will probably use the same endianness everywhere of course.

> B: byte order for header values (1-bit Boolean)

That's what the specification states wrt the byte order bit. 'header values' is to be interpreted as 'all values in the GeoPackage header that consist of more than one byte'. In practice that means this is applicable to the `srs_id` field and the `envelope` fields. `version` and `flags` are single byte values and `magic` is a sequence of byte values. Byte-order has no impact on those fields.

> I know that public comment has ended for 1.3, but if I still can make a proposal

That's up to @jyutzler. I haven't been involved with the GeoPackage SWG for many years.

**Comment by phidrho** [comment]
@pepijnve Thank you very much for the thorough explanation, now it's all clear. I have experience with Python and SQL, but I haven't been working with data on byte-level before, so it was kind of confusing.

@jyutzler I'll close the issue now, please consider the proposal if you think it makes sense.

**Comment by jyutzler** [comment]
Reopening this to try to clarify it a bit.

**Comment by phidrho** [comment]
> Reopening this to try to clarify it a bit.

I'm here if needed, you can also find me on skype under the same username.

**Comment by jyutzler** [comment]
@phidrho @pepijnve See #559 for the proposed merge request. Does this look right?
