### ISSUE TITLE
"ST_" in view st_geometry_columns

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/geopackage#550]
Although [double-quoted strings are accepted in SQLite](https://sqlite.org/quirks.html#double_quoted_string_literals_are_accepted), it probably would be better not to use them:

> The SQL standard requires double-quotes around identifiers and single-quotes around string literals. [...]
> 
> SQLite accepts both of the above. But, in an effort to be compatible with MySQL 3.x (which was one of the most widely used RDBMSes when SQLite was first being designed) SQLite will also interpret a double-quotes string as string literal if it does not match any valid identifier.
> 
> This misfeature means that a misspelled double-quoted identifier will be interpreted as a string literal, rather than generating an error. It also lures developers who are new to the SQL language into the bad habit of using double-quoted string literals when they really need to learn to use the correct single-quoted string literal form.
> 
> In hindsight, we should not have tried to make SQLite accept MySQL 3.x syntax, and should have never allowed double-quoted string literals. However, there are countless applications that make use of double-quoted string literals and so we continue to support that capability to avoid breaking legacy.
> 
> As of SQLite 3.27.0 (2019-02-07) the use of a double-quoted string literal causes a warning message to be sent to the error log.
> 
> As of SQLite 3.29.0 (2019-07-10) the use of double-quoted string literals can be disabled at run-time using the SQLITE_DBCONFIG_DQS_DDL and SQLITE_DBCONFIG_DQS_DML actions to sqlite3_db_config(). [...] 

When opening a GeoPackage file created with https://github.com/ngageoint/geopackage-java with [DB Browser for SQLite](https://sqlitebrowser.org/) 3.12.0, the error log contains `(28) double-quoted string literal: "ST_"`

When opening the same file with [Spatialite CLI](http://www.gaia-gis.it/gaia-sins/) version 5.0.0, and executing `select * from st_geometry_columns;`, I get `Error: no such column: ST_`.

Dropping the view and recreating it using single quotes solves that error. So the definition of the view in the spec should be updated (it is informative).

```sql
CREATE VIEW st_geometry_columns AS
  SELECT
    table_name,
    column_name,
    'ST_' || geometry_type_name,
    g.srs_id,
    srs_name
  FROM gpkg_geometry_columns as g JOIN gpkg_spatial_ref_sys AS s
  WHERE g.srs_id = s.srs_id;
```

**Comment by jyutzler** [comment]
Is this a problem with the GeoPackage Encoding Standard or the NGAGEOINT implementation? I _think_ the issue is on the implementation side, in which case the issue should be brought up with them. Please correct me if you think I'm wrong.

**Comment by bosborn** [comment]
I [updated the NGA library](https://github.com/ngageoint/geopackage-core-java/commit/351815bd933f3ad442340cf7571c607fe332784e) to use single quotes.  The [spec should be adjusted](https://www.geopackage.org/spec/#_gpkg_geometry_columns) to single quotes as well. The `geometry_type_name` column is also missing an _AS_ clause resulting in an unfortunate column name.

```
CREATE VIEW st_geometry_columns AS
  SELECT
    table_name,
    column_name,
    'ST_' || geometry_type_name AS geometry_type_name,
    g.srs_id,
    srs_name
  FROM gpkg_geometry_columns as g JOIN gpkg_spatial_ref_sys AS s
  WHERE g.srs_id = s.srs_id;
```

**Double Quotes**
![Screen Shot 2021-02-02 at 11 41 57 AM](https://user-images.githubusercontent.com/11667761/106647420-248be580-654c-11eb-9a1c-27f57f4fe932.png)

**Single Quotes**
![Screen Shot 2021-02-02 at 11 41 38 AM](https://user-images.githubusercontent.com/11667761/106647449-2e154d80-654c-11eb-8932-b83e48305e5f.png)

**Single Quotes with AS clause**
![Screen Shot 2021-02-02 at 11 43 05 AM](https://user-images.githubusercontent.com/11667761/106647487-3c636980-654c-11eb-8dbd-db12d1afafed.png)
