### ISSUE TITLE
Gridded Coverage Extension 16-bit PNG - Signed / Unsigned contradiction?

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/geopackage#551]
In section 6.2. Storage formats and grid cell values ( http://docs.opengeospatial.org/is/17-066r1/17-066r1.html#_storage_formats_and_grid_cell_values ) it says:

>  using PNG (16-bit, **signed** integer)

Requirement 13 says:

>  the data SHALL be 16-bit **unsigned** integer (single channel - "greyscale").

As far as I understand PNG only supports unsigned integers. From https://en.wikipedia.org/wiki/Portable_Network_Graphics :

> The permitted formats encode each number as an unsigned integer value using a fixed number of bits

It seems a proper fix would be to keep the requirement as-is but fix 6.2, but what are implementations currently doing?

Am I missing something?

**Comment by jyutzler** [comment]
We concur that a change is needed. We just need a pull request. Assigning to @ryanfranz.

**Comment by ryanfranz** [comment]
Pull request from https://github.com/ryanfranz/geopackage-tiled-gridded-coverage created.

**Comment by ryanfranz** [comment]
@jyutzler Changes have been merged, this can be closed

**Comment by jyutzler** [comment]
Closed via #575
