### ISSUE TITLE
Request to support additional data types in GeoPackage coverages

### ISSUE THREAD

**Issue by ryanfranz** [opengeospatial/geopackage#552]
CDB is considering the use of GeoPackage to store coverage data.  CDB currently uses a variety of data element types (in GeoTiff) to store coverage data.  I am requesting to be able to use these data types in a GeoPackage coverage tile:
* 8/16/32 bit signed integers
* 8 bit unsigned integer (16-bit integer is currently supported, but only for PNG)
* 32-bit floating point (already supported in GeoPackage coverages)
* 1 bit (will be used in CDB 1.2 when adopted, as a binary mask)

I think it would benefit the GeoPackage format to allow the use of GeoPackage coverages beyond a few narrow use cases that the existing formats allow.

**Comment by jyutzler** [comment]
We are tabling this so that @ryanfranz can produce a pull request containing proposed text. This is a substantive change that will require a SWG motion.

**Comment by ryanfranz** [comment]
Current Requirement 17:  A TIFF file storing tiled GeneralGridCoverage, class grid-regular, such as elevation data, SHALL have the 32-bit floating (FLOAT – 11) data type. This requirement constrains TIFF Section 19. 

Proposed changed Requirement 17:  A TIFF file storing tiled GeneralGridCoverage, class grid-regular, such as elevation data, SHALL have 32-bit floating (FLOAT - 11) data type or have a binary data type where the SampleFormat value of either 1 (unsigned integer), or 2 (signed integer) AND the BitsPerSample is either 8, 16, or 32.

I would also recommend adding a table to show the available data types after this change:
![image](https://user-images.githubusercontent.com/47611904/105127884-6c6c3080-5aa7-11eb-98cb-62e74da2e917.png)

I believe that this would be a minor revision change to the extension, as any earlier data would still be valid with this change.

**Comment by jyutzler** [comment]
The SWG agrees in principle to combine this and #553 into a single requirements class modeled on the TIFF requirements class.

**Comment by jyutzler** [comment]
This is closed by the updates in the proposed 1.1 of the Standard Extension.
