### ISSUE TITLE
Request to allow multiple channels in a GeoPackage Coverage

### ISSUE THREAD

**Issue by ryanfranz** [opengeospatial/geopackage#553]
A single channel coverage can cover a lot of data types, but not all data types.  In particular, there are data coverages that are comprised of multiple data values per grid cell, and designed that you need all the data elements to make use of this type of data.  My initial thought is that a layer that describes current wind conditions would be both wind cardinal direction and velocity.  In this case, it would be difficult to use either coverage without the other.

In CDB, we have coverages that represent the physical material of a grid on the ground or on a model, that consist of the material index and a percentage of that material.  Another use case is encoding elevation data based on a point elevation (not an average), where at lower resolutions we want to adjust the point's position (in latitude/longitude) as offsets from the grid cell corner.

If coverages were more flexible in this manner, then imagery could just become another coverage, and possibly contain non-visual bands (like Near Infrared (NIR) or Short-Wave Infrared (SWIR) data) too.

**Comment by jyutzler** [comment]
We are tabling this so that @ryanfranz can produce a pull request containing proposed text. This is a substantive change that will require a SWG motion.

**Comment by ryanfranz** [comment]
I will see how much the CDB SWG might want this change.  It might be ok to use multiple tile coverages for related data types, at the cost of increasing the number of rows in these tables.  We can table this issue for now.

**Comment by jyutzler** [comment]
The SWG agrees in principle to combine this and #552 into a single requirements class modeled on the TIFF requirements class.

**Comment by jyutzler** [comment]
Update: The requirements classes were refactored but the SWG agreed not to support this particular capability. Therefore this is a WON'T FIX.
