### ISSUE TITLE
Media type in spec vs media type at IANA

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/geopackage#554]
I noticed that the latest version of the spec says:

> GeoPackage now has a registered media type (formerly MIME type) of `application/geopackage+vnd.sqlite3`

but at IANA the media type is (or has been changed to) `application/geopackage+sqlite3` (thus without `vnd.`)

**Comment by jyutzler** [comment]
Wow. This is a change from https://github.com/opengeospatial/geopackage/issues/381.
