### ISSUE TITLE
TGCE ATS entries are mis-named

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#557]
See https://github.com/opengeospatial/geopackage-tiled-gridded-coverage/issues/43

**Comment by ryanfranz** [comment]
This looks ready to merge from https://github.com/jyutzler/geopackage-elevation/tree/cleanup
It should be ok for a corrigendum update to TGCE

**Comment by ryanfranz** [comment]
@jyutzler This can be closed, changes were merged by you.
