### ISSUE TITLE
superset of current standard

### ISSUE THREAD

**Issue by calvinmetcalf** [opengeospatial/geopackage#56]
it would be nice if geopackage could be a superset of the current [defacto standard for sqlite simple features](http://trac.osgeo.org/fdo/wiki/FDORfc16) which is already supported by qgis, gdal, tilemill etc.  browsing the spec quickly it looks like the main incompatibilities (besides, obviously, new features) are things like table names.  

The standard could be written such that geopackage level 1 *is* the current sqlite implementation, (possibly with some details filled in if you can't help yourself) while geopackage level 2 would be the closer to what is proposed here adding raster day and indices on top of the current thing. 

This would make it significantly easier to get it adopted by the community as instead of  coming out with a 3rd (or 4th depending on when arcmap 10.2 ships) sqlite based format, it's instead just formalizing what's already in use and taking it to the next level.

**Comment by jyutzler** [comment]
At the 3/31/15 SWG meeting we agreed to close this issue. The SWG previously decided to go with an alternative direction as @pepijnve describes.
