### ISSUE TITLE
TGCE - Requirement 21 still mentions Elevation

### ISSUE THREAD

**Issue by ryanfranz** [opengeospatial/geopackage#572]
Requirement 21 of the Tiled Gridded Coverage Extension still uses the word elevation, when it should use the term coverage.

This would be a minor corrigendum change to the extension.

**Comment by cnreediii** [comment]
Corrected on 3/17/21

**Comment by jyutzler** [comment]
This is closed by the updates in the proposed 1.1 of the Standard Extension.
