### ISSUE TITLE
Clarify existing requirements classes

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#576]
Right now there is a lack of precision in some of the [TGCE](http://docs.opengeospatial.org/is/17-066r1/17-066r1.html) requirements classes. I think there are way too many requirements classes right now. Maybe simplify it to two: 
 
1. Core (Requirements 1-13 / Section 7)
2. TIFF Encoding (Requirements 14-21 / Section 8)

Therefore Requirement 14 needs to get moved into the TIFF Encoding Requirements Class and rewritten in such a way that it can be supplanted by a more flexible (but harder to implement) Requirements Class as described by #552 and #553.

Carl Reed to take this on.

**Comment by cnreediii** [comment]
Proposed changes have been made. Awaiting Ryan review and additional input.

**Comment by ryanfranz** [comment]
Review details (that were also shared on the OGC email list:

Clause 7:
Requirement 10 still references elevation, needs to be more generic

It feels like there needs to be two encoding sections, one for PNG and one for Tiff

Requirement 13 requires integer data to only be stored as image/png, we were going to relax this requirement to cover tiff as well
Should PNG stay limited to 16-bit data (as in Requirement 13), or would it be useful to use 8-bit data types too?

TIFF Encoding
"Tiles are encoded as a single-band image using either one 32-bit floating point component per pixel. This implies a number of constraints which are listed below."
There is an either/or, but the or part is missing (for binary integer data)

Requirement 15 - I didn't see any other reference to "RectifiedGridCoverages" outside this requirement

Requirement 17 - Should mention that the SampleFormat tag can be 1 (unsigned integer), 2 (signed integer), or 3 (IEEE floating point)
Maybe remove the part about (FLOAT - 11), which is mentioned in the TIFF documentation, but does not exist as is within the TIFF file format
Requirement 17 is included twice in the document, a paragraph apart

Requirement 18 is ok.  Tiff supports something called differencing predictor (section 14 of the TIFF spec), to make LZW compress better on floating point data. CDB disallowed its use.  Does TGCE want to make it explicit whether it can be used or not

Requirements 19 and 20 are written as if it only applies to a specific type or class of data (such as elevation data) and not to all TGCE TIFF data.  I don't think we have to say what the TIFF is storing to restrict the way the data is structured (no multi-images and no tiling of the internal data array).

**Comment by cnreediii** [comment]
Corrected 10 and 15. Trying to figure out 13 :-)

**Comment by ryanfranz** [comment]
@cnreediii  - The way it is written, it sounds like there are cases where requirements 19 and 20 do not apply.  I agree with your statement, but just wanted to ask the question in case someone could misunderstand this requirement

**Comment by cnreediii** [comment]
@ryanfranz - Got it. I modified Req 18 and 19 to be more generic to any regular gridded coverage.

**Comment by cnreediii** [comment]
@ryanfranz - As to "Should PNG stay limited to 16-bit data (as in Requirement 13)". I believe that this requirement was based on the experience and recommendations of the participants in the GeoPackage Elevation Extension Interoperability Experiment (https://www.ogc.org/projects/initiatives/geopackageelev) but I would need to check. 

Again for Req 13 and for TIFF, what would the encoding be? 32 bit binary? I want to make sure before adding words to the Req. I did modify to make either or :-)

**Comment by ryanfranz** [comment]
@cnreediii  - Req 17 now says that TIFF can be float; or signed or unsigned at bit lengths of 8, 16, or 32.  I don't think you have to put all of that into Req 13, but Req 13 used to say that if you had integer data it had to be PNG and an unsigned 16 bit data type.  If we allow integer data in TIFF files (req 17), I think we have to turn around the requirement to read the other way, if you use PNG encoding, it has to be unsigned integer data at 16 bits.

Conceptually, I think you need to enumerate two different encodings of TGCE data.  TIFF has a section devoted to it, but PNG only has a brief mention or two.

**Comment by jyutzler** [comment]
This is closed by the updates in the proposed 1.1 of the Standard Extension.
