### ISSUE TITLE
/base/core/spatial_ref_sys/data_values_default not traceable to requirement

### ISSUE THREAD

**Issue by bradh** [opengeospatial/geopackage#58]
Further to https://github.com/opengis/geopackage/issues/38 (closed, but not fixed), the /base/core/spatial_ref_sys/data_values_default test requires that the srs_id (nee srid) and organization_coordsys_id (nee auth_srid) are both 4326, but the need for these to match is not traceable to the requirement (which doesn't specify any constraint on what the srs_id should be - it only says "Req 11: The gpkg_spatial_ref_sys table in a GeoPackage SHALL contain a record for
organization EPSG or epsg [B3] and organization_coordsys_id 4326 [13][14] for WGS-84..."

In addition, the specific WKT for SRS 4326 is not traceable to the REQ 11 (it may become traceable via the links to EPSG web sites, but would need at least a version number for the data set).

**Comment by jyutzler** [comment]
At the 3/31/15 SWG meeting we agreed to close this issue because we do not anticipating making any changes to the specification on this topic at this time.
