### ISSUE TITLE
data types of GeoPackage columns and views

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#590]
A few facts:
- Requirement 5 mentions "The columns of tables in a GeoPackage SHALL only be declared using one of the data types specified in table Table 1" . It only mentions tables, not views.
- Test case /base/core/container/data/table_data_types as currently written will run on tables or views registered in gpkg_contents, so testing more than req 5 as currently written
- pragma table_info(some_view) can only reports type names if the SELECT refers to explicit column of tables, not other expressions, even if doing an explicit type cast. Demo:
```
$ sqlite3
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> CREATE TABLE my_table(fid INTEGER PRIMARY KEY, txt TEXT, i INTEGER);
sqlite> CREATE VIEW my_view AS SELECT fid, txt, i, (txt || '_suffix') AS txt_suffix,
                               CAST((txt || '_suffix') AS TEXT) AS txt_suffix_cast,
                               CAST((i+1) AS INTEGER) as i_p_1_cast FROM my_table;
sqlite> pragma table_info(my_view);
0|fid|INTEGER|0||0
1|txt|TEXT|0||0
2|i|INTEGER|0||0
3|txt_suffix||0||0
4|txt_suffix_cast||0||0
5|i_p_1_cast||0||0
```

Options are:
- we keep req 5 as it is, but restrict table_data_types test case only to tables
- we extend req 5 to views, but that will make a number of uses of views non compliant

**Comment by jyutzler** [comment]
Maybe just a NOTE indicating that SQLite support for view data types is not robust enough to allow this requirement to be enforced for views?

**Comment by jyutzler** [comment]
During today's SWG there was support for the note idea so I will produce a PR.
