### ISSUE TITLE
Data type column declaration and actual content

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#591]
Requirement 5 put constraints on the data type declared for columns of a feature/attribute/tiles user table, but there is no requirement that rows in such tables should contain values that match that data type, and I couldn't find any requirement regarding that. Storing row values that don't match the declaration is very possible since data type declaration in CREATE TABLE statement is mostly a hint, but doesn't preclude from storing any type of value. So in a column declared INTEGER you could have rows would values would be TEXT, BLOB or FLOAT.

Demo:
```
sqlite> CREATE TABLE t(i INTEGER);
sqlite> INSERT INTO t VALUES('foo');
sqlite> SELECT * from t;
foo
```

Is it something we want to allow ? (besides the above dummy example, real world situations I've seen are with DATETIME content that doesn't match "YYYY-MM-DDTHH:MM:SS.SSSZ" given in table 1) If not, shouldn't requirement 5 be extended or an additional requirement created ?

**Comment by jyutzler** [comment]
Related to #558.
