### ISSUE TITLE
List of approved extensions on geopackage.org needs to be updated

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/geopackage#598]
The List of approved extensions on geopackage.org needs to be updated to include the extensions listed in [Annex F](https://docs.ogc.org/is/12-128r17/12-128r17.html#registered_extensions) of version 1.3 of the GeoPackage standard.

http://www.geopackage.org/extensions.html

**Comment by jyutzler** [comment]
Fixed by https://github.com/opengeospatial/geopackage/commit/5fe47fe75387c7d534412dd3d08be8a1f3d6eb58
