### ISSUE TITLE
Missing requirement regarding lowercase identifiers?

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/geopackage#603]
According to clause [Base](https://www.geopackage.org/spec130/#_base),

https://github.com/opengeospatial/geopackage/blob/50a28dd90635ad04154e9eb460b7924f15a13fb5/spec/core/1_base.adoc#L5

identifiers shall be lowercase. However, no separate, explicit, numbered requirement is present in the specification regarding this.

The line above that line also uses normative language, stating 

https://github.com/opengeospatial/geopackage/blob/50a28dd90635ad04154e9eb460b7924f15a13fb5/spec/core/1_base.adoc#L4

but those statements are enforced by requirements, such as e.g. [requirement 10](https://www.geopackage.org/spec130/#r10) and [requirement 29](https://www.geopackage.org/spec130/#r29).

And because there is no explicit requirement, no test is present in the ATS, and GeoPackage files using uppercase or camelcase identifiers can pass the test.

**Comment by heidivanparys** [comment]
Note: some sample files in https://github.com/opengeospatial/geopackage/tree/gh-pages/data use uppercase identifiers, those should be updated as well if the statement regarding lowercase identifiers is actually a requirement.

**Comment by jyutzler** [comment]
I think we agreed that we would specify all lowercase for identifiers specified in the standard, but that this constraint does not apply to user-defined identifiers. User-defined identifiers are easily discoverable and must be discovered to be used so this should not be an interoperability issue.

However, I would agree to some additional explanatory text. Any suggestions?

**Comment by heidivanparys** [comment]
> However, I would agree to some additional explanatory text. Any suggestions?

See https://github.com/heidivanparys/geopackage/commit/9839fa2d264c4d9169cc26c7ff988e0c560be1d3 for a suggestion.

**Comment by jyutzler** [comment]
@heidivanparys The SWG concurs with this update. Please issue a pull request and we will accept it.
