### ISSUE TITLE
QUESTION: are extra columns allowed in a tile pyramid user table ?

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geopackage#613]
Requirement 54 mentions "Every such tile pyramid user data table SHALL be structured consistently with Table Definition and EXAMPLE: tiles table Create Table SQL (Informative)"
Does that mean that such a table should contain *exactly* the 5 mentioned columns, or could it contain extra columns ?

Potential use case: adding an extra column with a timestamp, to use GeoPackage as a caching backend for a tile service

**Comment by jerstlouis** [comment]
@rouault as I understand it and from feedback I had before, unfortunately I think it does mean exactly.

However I can think of other use cases for this:

- "Scene ID" for an EO imagery data cube extension (could be a foreign key to a scene tables with additional metadata including time of image, satellite row/col path etc.)
- Support for additional dimensions as suggested in new [TileMatrixSet 2.0 informative annex](https://docs.opengeospatial.org/DRAFTS/17-083r3.html#annex-extending-additional-dimensions)

I guess in your scenario you could always have a separate time stamp table that includes with a column for tile ID and another for time stamps. It be even more practical if you are caching tiles from separate layers and you want to query across all of them ordered by time stamps...

**Comment by jyutzler** [comment]
We talked about this in the Nov. 2 SWG. The wording in the standard was deliberate. We don't want people messing with the schema of tables that are defined in the standard.

I think it would be best for interoperability if you implemented the desired capabilities through child tables and JOINs.

**Comment by rouault** [comment]
thanks for the answer.
