### ISSUE TITLE
NA Comments on Conceptual Logical Model draft

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#617]
See https://github.com/opengeospatial/NamingAuthority/issues/176#issuecomment-1110904418

**Comment by jyutzler** [comment]
The bit about Section 8 is valid and obviously the bibliography needs to be added or deleted. The bit about requirements numbering is explained by the note at the beginning of Section 8.

> Requirements are numbered to maintain alignment with OGC 12-128.

**Comment by ghobona** [comment]
Ok, noted. Thanks.

**Comment by jyutzler** [comment]
Proposed changes in https://github.com/opengeospatial/geopackage/pull/621/commits/07c738e33d76630fa8741fd871e27fe59b930aee.

**Comment by jyutzler** [comment]
closed by #634
