### ISSUE TITLE
Figure style

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/geopackage#622]
Comment in response to https://www.ogc.org/standards/requests/246:

The style of the figures is different in the section on Conventions and in the other sections, which is confusing.

The same line and arrowhead styles should be used, and the style should be the one from the UML spec. Preferably, the same colours should be used.

![image](https://user-images.githubusercontent.com/11427611/168813074-1dcebe9e-b8b9-4dc0-926d-3f68f0e75332.png)

**Comment by jyutzler** [comment]
I'm really struggling here. I was having a hard time rendering my PlantUML at all and temporarily switched to Mermaid. One of the downsides to that is the solid triangles in inheritance/realization.

I now have PlantUML working again and so I have fixed those graphical issues. However, the Conventions section uses inline PlantUML and for some reason that UML is rendered in a theme that is no longer published with the latest version. This is better but not perfect. See https://github.com/opengeospatial/geopackage/pull/621/commits/765c881c86356cc0533e251c2457903246893217.

 Argh free software!

**Comment by heidivanparys** [comment]
It is possible to get an EA license via OGC, perhaps in a future revision, that should be used to do the UML? See also the material from the Conceptual Modeling session at the TC meeting Madrid.

**Comment by jyutzler** [comment]
It would be possible to remove the inline notation and replace it with new implementations.

If someone was winning to volunteer an EA-based set of models, the SWG would accept it. As of writing, there is no such volunteer.
