### ISSUE TITLE
Definitions in 7.1 Core

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/geopackage#625]
Comment in response to https://www.ogc.org/standards/requests/246:

- The definition of “attribute” can be made more concise.
- The definition of “attribute type” seems to a definition of “attribute”?

A proposal for modified definitions (similar changes could be done for the other concepts in the conceptual model (“feature type”, etc.).

<dl>
  <dt>attribute</dt>
  <dd>characteristic of an entity</dd>
  <dd>[SOURCE: ISO 19101-1:2014, 4.1.12, modified — Generalized the definition to fit this concept.]</dd>

  <dt>attribute type</dt>
  <dd>characteristic of an entity type</dd>
  <dd>An attribute type has a name, a data type, and a value domain associated to it. No restrictions are implied as to the type of attributes a user-defined type may have. Not all entity types have attributes.</dd>

  <dt>entity</dt>
  <dd>individual item that is perceivable or conceivable</dd>
  <dd>Note 1 to entry: For the purposes of this standard, an entity is simply a unit of content contained in a GeoPackage. This is deliberately open-ended so as not to prejudice the content that a GeoPackage may contain.</dd>
  <dd>[SOURCE: Based on <a href="https://standards.iso.org/ittf/PubliclyAvailableStandards/c071954_ISO_IEC_21838-1_2021(E).zip">ISO/IEC 21838-1:2021</a>, <a href="https://www.iso.org/obp/ui#iso:std:iso-iec:21838:-1:ed-1:v1:en:term:3.1">3.1</a> and <a href="https://www.iso.org/obp/ui#iso:std:iso-iec:21838:-1:ed-1:v1:en:term:3.3">3.3</a>. In this document, “entity” is used to denote the concept that is is denoted “particular” in ISO/IEC 21838-1:2021].</dd>

  <dt>entity type</dt>
  <dd>class of entities having common characteristics</dd>
  <dd>[SOURCE: ISO 19156:2011, 4.7, modified — Generalized the definition to fit this concept.]</dd>
</dl>

**Comment by jyutzler** [comment]
Is b82bbb4 better?

**Comment by heidivanparys** [comment]
> Is [b82bbb4](https://github.com/opengeospatial/geopackage/commit/b82bbb45bd6e1190e1ccee0ab5f3737eec3b3eb2) better?

Yes, thanks.

**Comment by jyutzler** [comment]
Closed by #634
