### ISSUE TITLE
“Feature” vs “geographic feature”

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/geopackage#626]
Comment in response to https://www.ogc.org/standards/requests/246:

The document uses the term “feature” for what is usually called “[geographic feature](https://isotc211.geolexica.org/concepts/203/)” – feature associated with a location relative to the Earth – in ISO and OGC documents (see e.g. the OGC abstract specifications).

That leads to the inventing of the term “attributes set” in 7.4, with the note that “OGC 12-128 defined this concept as “attributes”. However, this conflicts with the standard definition of an attribute as a member of a class.”.

Wouldn't it be more in line with existing OGC and ISO documents to use the terms already established in the conceptual and logical model?

- 7.2: feature → geographic feature
- 7.4: attributes set → non-geographic feature
- 7.4: attributes set type → non-geographic feature type

![billede](https://user-images.githubusercontent.com/11427611/169004851-704ecf01-ad7c-4e95-bcfa-91a5c4b527d9.png)

**Comment by jyutzler** [comment]
Is 57f0895 better?

**Comment by heidivanparys** [comment]
> Is [57f0895](https://github.com/opengeospatial/geopackage/commit/57f0895e6b966a713d8866a7f289c10d38a43fd2) better?

Yes, thanks.

**Comment by cnreediii** [comment]
Hmmm. Channeling Ron Lake. The discussion as to whether the concept "feature" is geographic or not goes back two decades to when the WFS Standard was in development. Ron - and many others such as John Herring and myself - stated that a feature does not have to have location and/or geometry. A feature is a real world phenomenon and can be defined by a set of attributes with no location content. An interesting conundrum when working in a geospatial context :-) Anyway, this is why a GML Feature may not have an associated geometry- just attributes (or properties as Ron and others termed these).

So, I am not sure if we need to define a geographic feature and a non-geographic feature. A feature either has a geometry or not.  Much simpler.
