### ISSUE TITLE
Case sensitive for column names

### ISSUE THREAD

**Issue by latot** [opengeospatial/geopackage#637]
Hi, I know has been talked before, like in https://github.com/opengeospatial/geopackage/issues/375.

Personally, I think the column names should be case sensitive, here some reasons:

- Postgres is case sensitive
- MySQL in linux is case sensitive
- OSM uses case sensitive

Can't save any map is hard D:

I think this question is hard, because, if Geopackage uses case-sensitivity, open or upload maps in MySQL in windows or in SQLite can be harder. But maybe is better be case sensitive, because without case sensitive, we are not even able to save/extract the map from the case sensitive servers.

Well, there is not a only solution for this, there is options like a flag to know if the columns are case sensitive.

In my thoughts, Geopackage is great, because we can save almost any data and map and simply share and work, the column case sensitivity is the only case where I wasn't able to save data.

Can save the original data is great because we can have data traceability :)

Thx!

**Comment by jyutzler** [comment]
Unfortunately for you, case-insensitivity is imposed by the underlying SQLite library. Our hands are tied here.

**Comment by latot** [comment]
isn't there a tricky way for this? D:

**Comment by jyutzler** [comment]
Nope.
