### ISSUE TITLE
Comments on Separated WKT for Coordinate Reference Systems Extension (version 1.1)

### ISSUE THREAD

**Issue by bosborn** [opengeospatial/geopackage#641]
* Requirements are copied from the base GeoPackage spec and include 115, 145, 116, and 117.  Should these be changed to be local? 1, 2, 3, 4
* Requirement 45 - Change wording to specify all rows.  "SHALL have a row" -> "SHALL have rows" or "SHALL have all rows"
* Update Table 2 definition columns and/or NOTE.  The NOTE applies to the first extension row (version 1).  For version 1.1, I assume the URL would be http://www.opengis.net/doc/IS/geopackage-crs-wkt/1.1 or http://docs.opengeospatial.org/is/[VERSION]/[VERSION].html

I see the publication date [was updated](https://github.com/opengeospatial/geopackage/commit/5028c57ea95fbd42510ee66d2d9c1046b29ad83a) to/on 2022-10-14.  Is the generated version published yet?  And if so, should be added to [listed extensions](https://www.geopackage.org/extensions.html).

**Comment by jyutzler** [comment]
Regarding bullet #1, OGC policy is to retain requirements numbers wherever possible so we will not be renumbering.

We concur on bullets #2/3 and will make the update.

**Comment by jyutzler** [comment]
> Is the generated version published yet? And if so, should be added to [listed extensions](https://www.geopackage.org/extensions.html).

Updated. @bosborn
