### ISSUE TITLE
Wrong test query in gpkgext_relations Relation Name?

### ISSUE THREAD

**Issue by phidrho** [opengeospatial/geopackage#643]
Hi,

if I understood text from Requirement 8 properly:

> Each relation_name column in a gpkgext_relations row SHALL either match a relation_name from the Requirements Classes for User-Defined Related Data Tables in this or other OGC standards (e.g. media for [Media Requirement Class]), or be of the form x-<author>_<relation_name> where <author> indicates the person or organization that developed and maintains this set of User-Defined Related Tables.

Allowed `relation_name` are: 'features', 'simple_attributes', 'media', 'attributes', 'tiles', and custom name is optional, so test query in [gpkgext_relations Relation Name](https://docs.ogc.org/is/18-000/18-000.html#r8) should be changed from:

```sql
SELECT
    base_table_name,
    relation_name
FROM
    gpkgext_relations
WHERE
    (relation_name NOT IN ('features', 'simple_attributes', 'media')
    AND
    relation_name NOT LIKE 'x-%\_%' ESCAPE '\')
```

to:

```sql
SELECT
    base_table_name,
    relation_name
FROM
    gpkgext_relations
WHERE
    (relation_name NOT IN ('features', 'simple_attributes', 'media', 'attributes', 'tiles')
    OR
    relation_name NOT LIKE 'x-%\_%' ESCAPE '\')
```

**Comment by rouault** [comment]
I had proposed https://github.com/opengeospatial/geopackage/pull/631 some time ago regarding this

**Comment by phidrho** [comment]
> I had proposed #631 some time ago regarding this

Didn't see that, great!
Did I misunderstood test query or 'AND' should also be replaced with 'OR' inside WHERE clause.
Test is defined as 1. run a query, and **`2. Fail if returns any rows`**.

**Comment by rouault** [comment]
> Did I misunderstood test query or 'AND' should also be replaced with 'OR' inside WHERE clause.

the AND is correct AFAICS. A perhaps more natural, but equivalent way, would be to have the NOT as the topmost operator with OR inner it:  ``NOT( relation_name  IN ('features', 'simple_attributes', 'media', 'attributes', 'tiles') OR relation_name LIKE 'x-%\_%' ESCAPE '\' )``

**Comment by phidrho** [comment]
> > Did I misunderstood test query or 'AND' should also be replaced with 'OR' inside WHERE clause.
> 
> the AND is correct AFAICS. A perhaps more natural, but equivalent way, would be to have the NOT as the topmost operator with OR inner it: `NOT( relation_name IN ('features', 'simple_attributes', 'media', 'attributes', 'tiles') OR relation_name LIKE 'x-%\_%' ESCAPE '\' )`

Thanks, I just figured it out that with OR it would return other case in moment of testing (first or second).
