### ISSUE TITLE
Support multiple geometry columns

### ISSUE THREAD

**Issue by latot** [opengeospatial/geopackage#646]
Hi all, I think would be great to support multiple geometry columns, there is a lot of related spatial data, where this feature could simplify store properties and relations of the space (instead have ids everywhere)?.

https://gis.stackexchange.com/a/409478/196016

Thx!

**Comment by bosborn** [comment]
FYI #77

**Comment by jyutzler** [comment]
I'm sorry, @lalot, but the resolution in #77 is final on this topic. We have heard from a number of stakeholders that this capability would cause more problems than it solves.

See https://www.geopackage.org/guidance/modeling.html for more information.
