### ISSUE TITLE
gpkg_version() is not implemented

### ISSUE THREAD

**Issue by kirkktx** [opengeospatial/geopackage#647]
I want to see what version of the spec has been implemented.
I would expect this to be `select gpkg_version();`
However that's not implemented.
Is there some other way of retrieving the spec version?
These all work:
`select sqlite_version(); `
`select proj_version(); `
`select geos_version();`

**Comment by jyutzler** [comment]
See https://www.geopackage.org/spec130/#r2 for the way to do this. 

While we could theoretically add a function to the specification, there would be no way to add it to existing GeoPackages so I doubt this will happen.

**Comment by jratike80** [comment]
I think that `PRAGMA user_version` that works starting from GeoPackage version 1.2 is close to what is desired.

**Comment by jyutzler** [comment]
I will take an action to mention the use of `PRAGMA user_version` as a way to retrieve the GeoPackage Version. This would be an administrative change as part of a future revision.
