### ISSUE TITLE
Requirement 11 references are broken

### ISSUE THREAD

**Issue by nmtoken** [opengeospatial/geopackage#669]
> The record with an srs_id of 4326 SHALL correspond to [WGS-84](http://www.google.com/search?as_q=WGS-84) [[I15]](https://www.geopackage.org/spec131/index.html#I15) as defined by [EPSG](http://www.epsg.org/Geodetic.html) [[B3]](https://www.geopackage.org/spec131/index.html#B3) in [4326](http://www.epsg-registry.org/report.htm?type=selection&entity=urn:ogc:def:crs:EPSG::4326&reportDetail=long&title=WGS%2084&style=urn:uuid:report-style:default-with-code&style_name=OGP%20Default%20With%20Code) [[I13]](https://www.geopackage.org/spec131/index.html#I13)[[I14]](https://www.geopackage.org/spec131/index.html#I14).

**EPSG** link reference `http://www.epsg.org/Geodetic.html` no longer exists should probably be `https://epsg.or/home.html`

**4326** link reference `http://www.epsg-registry.org/report.htm?type=selection&entity=urn:ogc:def:crs:EPSG::4326&reportDetail=long&title=WGS%2084&style=urn:uuid:report-style:default-with-code&style_name=OGP%20Default%20With%20Code` no longer exists should probably be `https://epsg.org/crs_4326/WGS-84.html`

**Comment by jyutzler** [comment]
Thanks! I am pretty sure I can get this in under the wire for 1.4.0.

**Comment by jyutzler** [comment]
Closed by #670
