### ISSUE TITLE
Changing GeoPackage version in SQLite header

### ISSUE THREAD

**Issue by jamesresslernga** [opengeospatial/geopackage#689]
How does someone change the SQLite header to set the standard version of a GeoPackage?

From the specification, OGC GeoPackage Requirement 2, the version is set in the GeoPackage SQLite header: 

> ... A GeoPackage SHALL contain an appropriate value in "user_version" field of the SQLite database header to indicate its version. The value SHALL be a five-digit integer with a major version, two-digit minor version, and two-digit bug-fix.

•             For example, for GeoPackage Version 1.3.0 this value is 0x0000283C (the hexadecimal value for 10300).

•             From https://docs.fileformat.com/database/sqlite/ the user_version is 4 bytes in offset 60 .

I want to set the version of a GeoPackage SQLite file to 1.3.1 (00301) or to 1.4.0 (10400), which I think is 0x0000283D and 0x000028A0 in hex, respectively.

•             From https://docs.fileformat.com/database/sqlite/ the user_version is 4 bytes in offset 60 .

Looking for tools to change the SQLite header without writing code.

**Comment by rouault** [comment]
> How does someone change the SQLite header to set the standard version of a GeoPackage?

cf https://github.com/OSGeo/gdal/blob/c1016e7d8e127090ddb2c2687812c83c3ef88955/ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp#L195

**Comment by jamesresslernga** [comment]
Thank you . This command worked in SQLIte (DB Browser) to set GeoPackage standard version to 1.4.0 for a gpkg.
PRAGMA user_version = 10400;
