### ISSUE TITLE
REQ 30 inconsistent with REQ 22

### ISSUE THREAD

**Issue by bradh** [opengeospatial/geopackage#71]
The design of gpkg_geometry_columns is inconsistent (or perhaps just redundant) with the feature data model described in REQ 30. 

If there is only one geometry column, then the REQ 22 text "one row record for each geometry column in each vector feature user data table " doesn't make sense. Similarly, the gpkg_geometry_columns primary key being across (table_name, column_name) is not required because table_name would be sufficient.

More generally, this restriction is unfortunate in that it prevents "fall-back" implementations for extended (non-linear) geometry.

**Comment by jyutzler** [comment]
At the 3/31/15 SWG meeting we agreed to close this issue because we are not inclined to make any further schema changes at this time.
