### ISSUE TITLE
/opt/features/geometry_encoding/data/blob needs more definition

### ISSUE THREAD

**Issue by bradh** [opengeospatial/geopackage#72]
Test Case /opt/features/geometry_encoding/data/blob uses "ST_IsEmpty()" which is not defined within the scope of this option level. It is referenced within the RTree extension, but the exact definition of "empty geometry" in that RTree extension is not provided.

In particular, is it both sufficient and necessary that the Y flag in the GeoPackageBinaryHeader be set for geometry to be considered empty?

**Comment by jyutzler** [comment]
@bradh if we do not get further feedback on this issue it will be closed on April 14, 2015.

**Comment by bradh** [comment]
You've already said you won't make more changes...

**Comment by jyutzler** [comment]
@bradh We aren't planning to make any substantive changes to the core of the specification but we are interested in administrative changes including clarifications.
