### ISSUE TITLE
Mapping WKT/WKB to GeoPackage Geometry

### ISSUE THREAD

**Issue by bradh** [opengeospatial/geopackage#73]
REQ 11 provides two "undefined" entries.

Should geometries that do not have a specified spatial reference (e.g. those derived from WKT / WKB input, or from shapefiles without associated projection information) be mapped to srs_id = -1 or srs_id = 0?

**Comment by jyutzler** [comment]
At the 3/31/15 SWG meeting we agreed to close this issue as it looks like it has been resolved satisfactorily. Since 0 and -1 occur in the wild, the specification supports them but does not define their meaning.
