### ISSUE TITLE
Specific Implementation Questions: iOS, Android

### ISSUE THREAD

**Issue by rkurian** [opengeospatial/geopackage#75]
Hello, I work for Skyline Software, makers of the TerraExplorer 3D Client.  We are interested in implementing the GeoPackage standard for our mobile app development, but have run into a few questions.  The iOS environment is very touchy about security, preferring to generally keep the different applications separate.  Is there any plan or thought right now to how applications will manage to share the GeoPackage data? Any particular technique that is being considered at all (even at this early stage)?

We have pretty much the same question for Android devices, although there the security is more lenient.  Since we are actively working towards a release, of course we'd love to be able to have our software be good members of the community in terms of common behavior for the user.

Thanks!

**Comment by jyutzler** [comment]
One suggestion is to implement a server running locally on the device. The server connects to the file and other applications connect to the server. This pattern is commonly used in iOS development.

At the 3/31/15 SWG meeting we agreed to close this issue as it is more to do with application architecture than the GeoPackage standard itself.
