### ISSUE TITLE
Implementing Geopackage requires a $225 specification

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/geopackage#76]
As pointed out in https://gist.github.com/tmcw/fac12b6eb89cb28bb18f - to implement the geometry encoding you need `ISO/IEC 13249-3:2011`, which costs $225. This is a barrier for many people. Though there are many sample implementations of it'd be much better to have a way for people to get at that spec, or at least the portions relevant to geopackage.

Perhaps we could put them in an Annex?

**Comment by jyutzler** [comment]
This has been resolved. The references 9-11 http://www.geopackage.org/spec/#_normative_references_normative describe the required encodings and are not protected by a paywall.
