### ISSUE TITLE
Tileset examples

### ISSUE THREAD

**Issue by squishter** [opengeospatial/geopackage#84]
There really needs to be some official geopackage examples showing several types of tilesets.
- examples with different coordinate reference systems
- example(s) with a full top-to-bottom tileset (multiple zoom_levels, all of the same area)
- example(s) with a partial top-to-bottom tileset (multiple zoom_levels, higher zooms cover a small fraction of the lower zooms)
- example(s) with a single zoom_level, covering a larger area

The one current example that supposedly has a tileset doesn't.

The issue is, I've seen 3 different source's examples of geopackage, and each treats matrix_width, matrix_height, zoom_level, pixel_x_size and pixel_y_size differently.  Without official examples to compare/test against, it is impossible to know which is correct.  The partial example in Annex F is somewhat useful, but far from comprehensive.

**Comment by jyutzler** [comment]
I agree that we need to provide more samples. There are some here:
http://www.geopackage.org/#sampledata
and more will be added, but I don't believe this covers all of the bases.

**Comment by squishter** [comment]
Yeah, but none of the downloadable samples actually contain image tiles.  Even the one labeled as "Haiti OpenStreetMap tiles and point features" only contains features.  The NZ source may, but there is no obvious means of downloading the geopackages themselves, only the data repackaged into other types (a zip file full of jpegs for instance). 


     On Thursday, March 19, 2015 10:00 AM, Jeff Yutzler <notifications@github.com> wrote:
   

 I agree that we need to provide more samples. There are some here:
http://www.geopackage.org/#sampledata
and more will be added, but I don't believe this covers all of the bases.—

**Comment by jyutzler** [comment]
@squishter I ask for your patience here. I have recently taken over as chairman of this working group. We have a new reference implementation that contains image tiles and it should be uploaded soon. We used it as part of an interoperability experiment that we just finished.

**Comment by jyutzler** [comment]
@squishter I know it has taken too long but we have finally posted some image data. See http://www.geopackage.org/#sampledata
