### ISSUE TITLE
Shapefile Challenge

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#86]
A community in Europe has [issued](http://giswiki.hsr.ch/Shapefile) what they call the Shapefile Challenge. They would like to identify a replacement for Shapefile over the course of the next year and present their findings at a conference in March 2016.  

We feel that GeoPackage is a fine replacement for Shapefile particularly in scenarios where a text-based encoding like GeoJSON is not ideal. Following are the 7 weaknesses of Shapefile as identified in the Wiki and where GeoPackage stands.

Issue | GeoPackage
----- | ----------
>8-character names |Yes
Files greater than 2GB |Yes
Single file structure |Yes
More than one geometry per table|No ([more info](https://github.com/opengeospatial/geopackage/issues/77))
MultiGeometries and GeometryCollection|Yes/No
Arc and topology support |No
Schema |Yes

We acknowledge that GeoPackage is a relatively new format and it will take some time for the software to catch up. Meanwhile we stand available to answer any questions you may have. For now I have documented this as an issue. If necessary I will migrate it to a FAQ, Wiki, or some other format.

**Comment by pepijnve** [comment]
@jyutzler when we were doing the GeoPackage webinar we came up with some additional GeoPackage benefits at Luciad. The one's I remember are listed below. Perhaps Thomas can ask Frank if we remembers any others. I don't have the slide deck from the webinar anymore, but if you can get a hold of it, the last slide had a table comparing some formats. Might be useful to pass on to this group.

- All the functionality of SQLite for free. This resolves issues like https://github.com/mapbox/geobuf/issues/37 automatically without having to reinvent solutions.
- Transactional datastore. That's actually the same as the above, but deserves its own bullet point :)
- Efficient in place updates. Shapefile is problematic for variable length fields. Geojson and Geobuf have the same limitation.
- Embedded, non-properietary indices on geometry and non-geometry properties. Shapefile's .sbn format is not documented. Even Rouault reverse engineered it I believe, but that's suboptimal. Geojson and Geobuf do not have indexes.
- Efficient retrieval of individual elements by id. SQLite can use its rowid index to do a binary search. Geojson and Geobuf need to do a linear scan.
- UTF-8 or UTF-16 text encoding mandatory; chosen encoding embedded in database

**Comment by jyutzler** [comment]
Closing this as it is not actionable at this time.
