### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#89]
https://github.com/opengeospatial/geopackage/blob/master/LICENSE.md on GitHub indicates that this document is not an OGC standard. This file needs to be updated with the correct information.

**Comment by jyutzler** [comment]
@cholmes presumably the license for the GPKG GH repo should be different from the license for the standard itself. How should this be handled?

**Comment by KRyden** [comment]
The license used in an OGC Standard is also applicable in the context of that evolving standard hosted on a github site.  The current license file in the Geopackage repo is not appropriate any longer - that file was the one in use when the initial standards working group was formed with contributors listed.  At this point, it is an OGC standard with the IP owned by the OGC - the standard OGC license should be posted.

**Comment by jyutzler** [comment]
https://github.com/opengeospatial/geopackage/commit/df8ed6f2f1a4a6ecd78823eca8a95c864a1bf318
