### ISSUE TITLE
Constraining TIFF

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#91]
Barring a "Dewey Beats Truman" moment, the SWG vote for [TIFF](http://partners.adobe.com/public/developer/en/tiff/TIFF6.pdf) as the encoding for elevation tiles will pass. The next step is identifying what options we will allow. Let's go ahead and start that discussion.
   1. Byte order? (Can we pick one?)
   1. Samples per pixel (1)
   1. What numeric types?
      * 16-bit unsigned integers (and if we use these, how will we set the gain and offset?)
      * 32-bit floating point
      * others?
   1. Compression?
      * TIFF supports LZW compression. Is this capability beneficial? BTW, I see no indication that it is invalid for floating point values, though I can't say whether it is as effective.
   1. Other required parameters (do we need to specify ALL required parameters or can we safely defer to the TIFF spec for that)
   1. Prohibited parameters
      * Subfiles or internal tiles (I think we can all agree on that) 
      * others?

Note @rouault's comments here: https://github.com/opengeospatial/geopackage/issues/85#issuecomment-94270598

**Comment by jyutzler** [comment]
At today's SWG meeting, we agreed on the following:
   1. Byte order: Since use in the community appears to be arbitrary, we will not specify it and allow it to be handled by the specification. Compliant clients shall support either.
   2. Samples per pixel: 1
   3. We require both 16-bit unsigned and 32-bit floating point. Since there are so many ancillary parameters (NULL, unit of measure, etc.) we decided to break this out into a separate issue #93.
   4. TIFFs MAY contain LZW compression so clients SHALL support the extension.
   5. No further parameters identified.
   6. Agreed to prohibit subfiles and internal tiles. No further parameters identified.

**Comment by rouault** [comment]
16-bit unsigned doesn't seem to be the most appropriate choice. Negative values can exist, so should rather be 16-bit signed.

**Comment by jyutzler** [comment]
@rouault The feedback from SWG participants is that existing elevation software doesn't work that way in practice. Instead you define a unit of measure/scale and measure from a nadir.  This will be described further in #93.

**Comment by rouault** [comment]
For example at SRTM data at ftp://srtm.csi.cgiar.org/SRTM_V41/SRTM_Data_GeoTiff/  is definitely Int16. Is the elevation discussed here a DEM or something else ?

**Comment by jyutzler** [comment]
Reopening to discuss at next week's SWG meeting.

**Comment by jyutzler** [comment]
At today's SWG meeting we decided that signed INT was a valid requirement. In addition we could not identify any compelling reason to retain both signed and unsigned INT. Now the valid data types are 32-bit float and 16-bit signed INT.
