### ISSUE TITLE
Generate corrigendum automatically

### ISSUE THREAD

**Issue by pepijnve** [opengeospatial/geopackage#92]
Is there any interest in automating the corrigendum generation process? I did some quick research and I think this should be feasible using `wdiff`. I saw that Joe insert `<ins>` and `<del>` tags around spans that have been edited. `wdiff --start-delete +++<del> --end-delete </del>+++ --start-insert +++<ins> --end-delete </ins>+++` should get you about the same result.
An additional post processing step will be needed for the footnotes, but that's about it.

If this part is scripted on Travis where the HTML is generated then it should be pretty easy to host multiple versions of the spec in parallel, with and without diffs compared to previous versions.

**Comment by jyutzler** [comment]
This isn't really a SWG issue, more of an OGC issue. @gbuehler if these processes are documented, we might be able to help streamline them. What do you think?

**Comment by jyutzler** [comment]
This is overcome by events since we are no longer putting revision marks in the posted document.
