### ISSUE TITLE
Schema for elevation domain description

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#93]
In #91 we determined the need for a separate table to describe the elevation domain details. This issue is to describe the details of that table. The issue is that we will invariably need to add additional columns to the tile set description table. However, the specifics of those columns will vary from coverage type to coverage type. We anticipate that others will want to extend the tile structure similarly but will need entirely different ancillary data. Separating this data into a separate table allows arbitrary extensions to coexist within the same database.

**Comment by jyutzler** [comment]
At today's SWG meeting, we came up with the following:

|Column Name|Type|Description|Null|Default|Key|
|--------|--------|--------|--------|--------|--------|
|id|INTEGER|Autoincrement primary key|no||PK|
|datatype|TEXT|'float' or 'integer'|no||
|uom|TEXT|as per http://aurora.regenstrief.org/UCUM|no||
|scale|REAL||yes|1||
|offset|REAL||yes|0||
|precision|REAL||yes|if datatype is integer then 1, otherwise undefined||
|data_null|REAL||yes|||
|data_missing|REAL||yes|||

Note: the last two were identified after the meeting.

How does this look? I would like to resolve this issue no later than May 12.

**Comment by jyutzler** [comment]
Something we didn't discuss today is elevation classification (bare-earth, first return, etc.)

**Comment by jyutzler** [comment]
5/12 SWG: We will go with this for now and review further when we implement.
Elevation classification can go into the ISO metadata. Will digging this out be an issue? We don't really know yet.

**Comment by pepijnve** [comment]
@jyutzler sorry for only commenting after you just closed this.

- How is this linked to the data table? There doesn't seem to be anything that can be used to perform a join.
- Is a finite list of values a wise idea? It feels like this is something that could/will be extended going forward. It's a bit unsql-like but perhaps a more generic key-value table is more appropriate here?
