### ISSUE TITLE
Complex Geometries

### ISSUE THREAD

**Issue by jyutzler** [opengeospatial/geopackage#94]
Does GeoPackage support vector datasets beyond simple geometries?  I've heard we might need to extend the current standard to include complex geometries used to support complex relationships.

Note: This came in over email. I am entering it here so that it is available publicly.

**Comment by jyutzler** [comment]
I don't know of any technical limitations that would prevent us from supporting complex geometries and/or relationships within GeoPackage. It would have to be implemented as an extension because there is no appetite in the Standards Working Group (SWG) for supporting what most would consider to be an edge case as part of the core standard. Generally speaking, there are two paths to getting this to happen:

### Top Down
   * The SWG agrees to produce the extension and hashes out the technical details.
   * The SWG produces a discussion paper to describe the intent and proposed approach. (This step is optional but it is often useful to gauge community interest and solicit feedback.)
   * At least three vendors (one of which is open source) produce implementations supporting the approach. As part of this process, the proposed approach is refined.
   * The extension is approved either by itself or as part of a revision to the core standard.
   * The extension is reviewed, profiled (if needed), and approved by the ASG and NSG.

We are going through this process right now to create an extension for GeoPackage to support tiled gridded elevation data.

### Bottom Up
   * A community of interest independent of the SWG defines a need and produces a prototype capability and relevent technical artifacts (e.g., profile or extension description).
   * Upon satisfactory completion, the artifacts are presented to NSG for review and approval.
   * The document works its way up the chain to ASG and then to OGC.

This is what is happening in KML / Common Overlay arena and it may be the right path for this task as well unless we can find other groups in the geospatial community who are interested in the capability.

**Comment by kjbacke** [comment]
Classification: UNCLASSIFIED
Caveats: NONE

I recall this topic of Geopackage support for complex geometries came up in the Geopackage SWG.  As I recall the discuss including the following questions:
	1) When and how often complex geometries are needed and for what applications/domains.  Two of working group members stated they did not typically utilize complex geometries for the vast majority of feature data applications.  At the SWG meeting none of the participants express a strong use-cases and none of the geospatial/GIS vendors expressed a need for inclusion of complex geometries in the Geopackage specification.  However, it was noted that the SWG may be required to readdress this topic if a strong use-case is presented for a specific domains such as large-scale urban datasets or aeronautical dataset that may require complex feature geometries.
	2) What would be the basis for defining complex geometries.  The Geopackage standard currently embraces the OGC Simple Feature specification which specify a base Geometry class with subclasses for Point, Curve, Surface and GeometryCollection.  If the SWG was going to entertain including complex geometries in the Geopackage specification it would look to adopt a formal standard that specifies complex geometries or other documentation generally accepted by the community.

--Kevin Backe 

-----Original Message-----

**Comment by jyutzler** [comment]
5/12 SWG: We prefer to stick with Simple Features. Keeping things the same will be cleaner. If the Simple Features specification changes we can look into that.
