### ISSUE TITLE
Sample provided may be incorrect

### ISSUE THREAD

**Issue by squishter** [opengeospatial/geopackage#96]
The sample recently provided at "https://portal.opengeospatial.org/files/60628" may be incorrect depending on how matrix_width and matrix_height columns in the gpkg_tile_matrix table are supposed to be populated.

In <b>Section 2.2.7.1.1</b> Table Definition, <b>Table 9</b> it states:
"matrix_width   Number of columns (>= 1) in tile matrix at this zoom level" and
"matrix_height   Number of rows (>= 1) in tile matrix at this zoom level"

Yet in <b>Section 2.2.7.1.2</b> Table Data Values it states:
"The gpkg_tile_matrix table or view MAY contain row records for zoom levels in a tile pyramid user data table that do not contain tiles."

 This, and the way matrix width and height are defined in the WMTS spec(http://portal.opengeospatial.org/files/?artifact_id=35326), implies to me that matrix_width and matrix_height are supposed to represent the <I>potential</I> number of tiles for this matrix given a matrix set's bounds.  Otherwise, how can you have an record in gpkg_tile_matrix with no tiles that represent that record, and still have matrix_width and matrix_height be non-zero.

The ERDC_Whitehorse_Geopackage.gpkg sample, however, has matrix_width and matrix_height representing the <I>actual</I> number of tiles provided for the matrix at this zoom_level.

**Comment by LLambertRGi** [comment]
That geopackage was created with an old version of the tiling software that had the exact bug that you're describing.  It also fails to set the application ID field in the SQLite header block.  We're regenerating the tiles with the latest tools to correct these issues.

**Comment by jyutzler** [comment]
I apologize for the delays here. There is an updated GeoPackage but OGC staff have not yet gotten it uploaded. Hopefully you can download the updated file here: 
https://drive.google.com/open?id=0ByvLbbvwoxUjREhlbGZyWVpNeG8&authuser=0

**Comment by joegc** [comment]
This has been completed and the site has been updated.. The new file is now available at https://portal.opengeospatial.org/files/63156
